### ISSUE TITLE
org.springdoc:springdoc-openapi-ui:1.5.3 relies on a method that does not exist

### ISSUE THREAD

**Issue by MusikPolice** [springdoc/springdoc-openapi#1057]
**Describe the bug**
When I try to start my web service after adding the `springdoc-openapi-ui` dependency, the service fails to start with the following error message:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    org.springframework.boot.web.embedded.netty.NettyReactiveWebServerFactory.createHttpServer(NettyReactiveWebServerFactory.java:163)
The following method did not exist:
    'reactor.netty.transport.Transport reactor.netty.http.server.HttpServer.runOn(reactor.netty.resources.LoopResources)'
The method's class, reactor.netty.http.server.HttpServer, is available from the following locations:
    jar:file:/C:/Users/musikpolice/.gradle/caches/modules-2/files-2.1/io.projectreactor.netty/reactor-netty/0.9.14.RELEASE/fc8f50c577145dca913c6fcd93864b061da43862/reactor-netty-0.9.14.RELEASE.jar!/reactor/netty/http/server/HttpServer.class
The class hierarchy was loaded from the following locations:
    reactor.netty.http.server.HttpServer: file:/C:/Users/musikpolice/.gradle/caches/modules-2/files-2.1/io.projectreactor.netty/reactor-netty/0.9.14.RELEASE/fc8f50c577145dca913c6fcd93864b061da43862/reactor-netty-0.9.14.RELEASE.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of reactor.netty.http.server.HttpServer
```
It looks to me as though springdoc-openapi is expecting a particular version of Springboot and/or Netty, but I can't find any documentation that says which versions of those libraries it is compatible with.

**To Reproduce**
Following [the instructions in the project readme](https://github.com/springdoc/springdoc-openapi#getting-started), I added the following to my `build.gradle` file:
```
implementation "org.springdoc:springdoc-openapi-ui:1.5.3"
```
This is an existing project based on Springboot 2.3.6.RELEASE, and as you can see in the error message above, we have `io.projectreactor.netty:reactor-netty:0.9.14.RELEASE` on our classpath.

**Expected behavior**
I would like to use `springdoc-openapi-ui` and the `openapi-gradle-plugin` to generate an OpenApi json file that describes my existing RESTful API. After adding the `springdoc-openapi-ui` dependency, my application won't start at all.

**Comment by MusikPolice** [comment]
While troubleshooting, I added `implementation "io.projectreactor.netty:reactor-netty:1.0.3"` to my `build.gradle` file, and that got me past the error message in the OP, but then I got:
```
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
	at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:358)
	at org.springframework.core.MethodIntrospector.selectMethods(MethodIntrospector.java:72)
Caused by: java.lang.IllegalStateException: Failed to introspect Class [org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@2f333739]
	at org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping.detectHandlerMethods(AbstractHandlerMethodMapping.java:206)
	at org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping.initHandlerMethods(AbstractHandlerMethodMapping.java:189)
	at org.springframework.web.reactive.result.method.AbstractHandlerMethodMapping.afterPropertiesSet(AbstractHandlerMethodMapping.java:157)
	at org.springframework.web.reactive.result.method.annotation.RequestMappingHandlerMapping.afterPropertiesSet(RequestMappingHandlerMapping.java:126)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1847)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 37 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/http/HttpServletRequest
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
```

Which appears to refer to the [javax.servlet.http.HttpServletRequest object](https://docs.oracle.com/javaee/6/api/javax/servlet/http/HttpServletRequest.html), so I added another dependency to my `build.gradle` file:
```
implementation "javax.servlet:servlet-api:2.5"
```

Following this, I got a bean naming error when starting the service:
```
The bean 'requestMappingHandlerAdapter', defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springframework/web/reactive/config/DelegatingWebFluxConfiguration.class] and overriding is disabled.

Action:
Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

Continuing down the rabbit hole, I added `spring.main.allow-bean-definition-overriding=true` to my `application.properties` file, and then ran into yet another class not found error, this time looking for `javax.servlet.DispatcherType`.

Can you please clarify what the actual dependencies of springdoc-openapi-ui are? The readme makes this sound very easy, but I'm not finding that to be the case.

**Comment by MusikPolice** [comment]
Solved the problem. Our project uses Spring webflux,  not Spring web mvc. I switched to 
```
implementation "io.projectreactor.netty:reactor-netty:1.0.3"
implementation "org.springdoc:springdoc-openapi-webflux-ui:1.5.4"
```
and was able to get the `/v3/api-docs` and `/swagger-ui.html` endpoints working.

**Comment by bnasslahsen** [comment]
@MusikPolice, 

 Please look at the [documentation for webflux](https://springdoc.org/#spring-webflux-support)
