### ISSUE TITLE
StackOverflowError thrown when POJO has a LocalTime field

### ISSUE THREAD

**Issue by DeepakAgr1411** [springdoc/springdoc-openapi#1061]
StackOverflowError exception is thrown on first load of swagger UI page when POJO has a java.time.LocalTime field. Swagger UI page fails to startup.

![image](https://user-images.githubusercontent.com/69033428/107937770-684e0880-6faa-11eb-9078-e9b4f590f835.png)

Attaching a sample project to reproduce this.
[demo.zip](https://github.com/springdoc/springdoc-openapi/files/5981020/demo.zip)

Below is the exception stacktrace: 
`java.lang.StackOverflowError: null
	at java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[na:1.8.0_261]
	at com.fasterxml.jackson.databind.util.LRUMap.get(LRUMap.java:68) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:1366) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1299) ~[jackson-databind-2.11.4.jar:2.11.4]
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:698) ~[jackson-databind-2.11.4.jar:2.11.4]
	at io.swagger.v3.core.util.PrimitiveType.fromType(PrimitiveType.java:347) ~[swagger-core-2.1.6.jar:2.1.6]
	at org.springdoc.core.MethodParameterPojoExtractor.isSwaggerPrimitiveType(MethodParameterPojoExtractor.java:204) ~[springdoc-openapi-common-1.5.4.jar:1.5.4]
	at org.springdoc.core.MethodParameterPojoExtractor.lambda$isSimpleType$4(MethodParameterPojoExtractor.java:193) ~[springdoc-openapi-common-1.5.4.jar:1.5.4]
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source) ~[na:1.8.0_261]
	at org.springdoc.core.MethodParameterPojoExtractor.isSimpleType(MethodParameterPojoExtractor.java:193) ~[springdoc-openapi-common-1.5.4.jar:1.5.4]
	at org.springdoc.core.MethodParameterPojoExtractor.fromGetterOfField(MethodParameterPojoExtractor.java:127) ~[springdoc-openapi-common-1.5.4.jar:1.5.4]
	at org.springdoc.core.MethodParameterPojoExtractor.lambda$extractFrom$0(MethodParameterPojoExtractor.java:114) ~[springdoc-openapi-common-1.5.4.jar:1.5.4]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source) ~[na:1.8.0_261]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[na:1.8.0_261]
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[na:1.8.0_261]`

**Comment by bnasslahsen** [comment]
@DeepakAgr1411, 

 First way, by setting, using springdoc-openapi, without any conversion:

```java
	static {
		SpringDocUtils.getConfig().addSimpleTypesForParameterObject(LocalTime.class);
	}
```

Second way, by setting using swagger-core, with conversion:
```java
	static {
			PrimitiveType.enablePartialTime();
	}
```

**Comment by sergey-volkov-lm** [comment]
@bnasslahsen Hello. Seems like same approach does not work with ZoneOffset.
`SpringDocUtils.getConfig().addSimpleTypesForParameterObject(ZoneOffset.class)` leads to field being ignored in api-docs.
`PrimitiveType.customClasses().put("java.time.ZoneOffset", PrimitiveType.STRING)` - same, ignored.

**Comment by bnasslahsen** [comment]
@sergey-volkov-lm, 

 When you use @ParameterObject annotation, you convert your fields to a method parameter.
 `ZoneOffset` extends `ZoneId` which is an ignored method parameter type by springdoc-openapi by default.
 
 Here is the [full list of ignored types](https://springdoc.org/#what-are-the-ignored-types-in-the-documentation).
 And this is a sample syntax to disable it.

```
static {
	SpringDocUtils.getConfig().addSimpleTypesForParameterObject(ZoneOffset.class);
	SpringDocUtils.getConfig().removeRequestWrapperToIgnore(ZoneId.class);
}
```
