### ISSUE TITLE
NullPointerException when no schemas exist

### ISSUE THREAD

**Issue by mhofer117** [springdoc/springdoc-openapi#1113]
**Describe the bug**
We startet with a minimal API, which so far does not provide any schemas - however there are void endpoints that should be available on the Swagger-UI.
Unfortunately, this produces the following exception when loading /v3/api-docs:
```
Caused by: java.lang.NullPointerException: null
        at org.springdoc.core.SpringDocConfiguration.lambda$propertiesResolverForSchema$1(SpringDocConfiguration.java:299)
        at org.springdoc.core.SpringDocConfiguration$$Lambda$1189/0x0000000001878680.customise(Unknown Source)
        at org.springdoc.api.AbstractOpenApiResource.lambda$null$3(AbstractOpenApiResource.java:281)
        at org.springdoc.api.AbstractOpenApiResource$$Lambda$1530/0x00000000a80d9ab0.accept(Unknown Source)
        at java.base/java.util.ArrayList.forEach(Unknown Source)
        at org.springdoc.api.AbstractOpenApiResource.lambda$getOpenApi$4(AbstractOpenApiResource.java:281)
        at org.springdoc.api.AbstractOpenApiResource$$Lambda$1529/0x00000000a80d96c0.accept(Unknown Source)
        at java.base/java.util.Optional.ifPresent(Unknown Source)
        at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:281)
        at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:181)
```

**To Reproduce**
- What version of spring-boot you are using? 2.3.5.RELEASE
- What modules and versions of springdoc-openapi are you using?
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-kotlin</artifactId>
            <version>1.5.0</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-security</artifactId>
            <version>1.5.0</version>
        </dependency>
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
  Actual Result: 500 Internal Server Error (NPE)
  Expected Result: Working specification with no schemas
- Provide with a sample code (HelloController) or Test that reproduces the problem
To reproduce, create a single restcontroller with only Void return types (this one is in Kotlin):
```
@RestController
@RequestMapping("/api/v1/test")
class ExampleController() {

    companion object {
        val LOG: Logger = LoggerFactory.getLogger(ExampleController::class.java.name)
    }

    @PostMapping("/test")
    fun testEndpoint(): ResponseEntity<Void> {
        return ResponseEntity.noContent().header("Content-Length", "0").build()
    }
}
```

**Expected behavior**
Ideally the API-Spec can be loaded even if there are no schemas / only void endpoints.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@mhofer117, 

 Please use the last stable version, as per today: `v1.5.6` before reporting any issue.
 This ticket will be closed, and can be reopened if you have any updates.

**Comment by mhofer117** [comment]
I just testet with v1.5.6 and the issue is the same:
```
Caused by: java.lang.NullPointerException: null
	at org.springdoc.core.SpringDocConfiguration.lambda$propertiesResolverForSchema$1(SpringDocConfiguration.java:310)
	at org.springdoc.core.SpringDocConfiguration$$Lambda$1265/0x0000000000000000.customise(Unknown Source)
	at org.springdoc.api.AbstractOpenApiResource.lambda$null$5(AbstractOpenApiResource.java:296)
	at org.springdoc.api.AbstractOpenApiResource$$Lambda$1524/0x0000000000000000.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.springdoc.api.AbstractOpenApiResource.lambda$getOpenApi$6(AbstractOpenApiResource.java:296)
	at org.springdoc.api.AbstractOpenApiResource$$Lambda$1523/0x0000000000000000.accept(Unknown Source)
```
```

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-kotlin</artifactId>
            <version>1.5.6</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-security</artifactId>
            <version>1.5.6</version>
        </dependency>
```
