### ISSUE TITLE
Cannot render primitive wrapper with @ParameterObject

### ISSUE THREAD

**Issue by VuDo98** [springdoc/springdoc-openapi#1142]
**Describe the bug**
When I use this method signature: 
@PostMapping()
public void create(@ParameterObject Long id, @RequestBody Object o)
I get `java.lang.StackOverflowError`

**To Reproduce**
I use the latest version of springdoc and no additional configuration than default.

**Expected behavior**
For spring, it will be able to pick up the query param and correctly map it to Long class.

Expected Swagger page:
Show page with query param `id` that map to Long class

expected generated URL: http://host/?id=1
body: {}

**Screenshots**
Truncated unnecessary log.
```
Caused by: java.lang.StackOverflowError: null
	at com.fasterxml.jackson.databind.type.TypeFactory._fromClass(TypeFactory.java:1355)
	at com.fasterxml.jackson.databind.type.TypeFactory._fromAny(TypeFactory.java:1299)
	at com.fasterxml.jackson.databind.type.TypeFactory.constructType(TypeFactory.java:698)
	at io.swagger.v3.core.util.PrimitiveType.fromType(PrimitiveType.java:347)
	at org.springdoc.core.MethodParameterPojoExtractor.isSwaggerPrimitiveType(MethodParameterPojoExtractor.java:235)
	at org.springdoc.core.MethodParameterPojoExtractor.lambda$isSimpleType$5(MethodParameterPojoExtractor.java:224)
	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:528)
	at org.springdoc.core.MethodParameterPojoExtractor.isSimpleType(MethodParameterPojoExtractor.java:224)
	at org.springdoc.core.MethodParameterPojoExtractor.fromGetterOfField(MethodParameterPojoExtractor.java:134)
	at org.springdoc.core.MethodParameterPojoExtractor.lambda$extractFrom$1(MethodParameterPojoExtractor.java:121)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
```

**Comment by bnasslahsen** [comment]
@VuDo98, 

The usage of `@ParameterObject` is wrong. This annotation **extracts fields** from parameter object. 
You should simply use `@Parameter` swagger standard annotation instead .

```java
	@PostMapping(value = "/persons")
	public void create(@Parameter(in = ParameterIn.QUERY) Long id, @RequestBody Object o){}
```

**Comment by VuDo98** [comment]
@bnasslahsen I raised this issue because I actually use generic there instead of Long. Some entity have a composite key which works here. Some only have a auto generated Long id.

**Comment by VuDo98** [comment]
@bnasslahsen tbh, I wonder why there is @ParameterObject. Isn't it possible to convert the POJO to query params since spring is doing it already?

**Comment by bnasslahsen** [comment]
@VuDo98, 

 I think i have already answered you, about the sample code you have provided.
 Please read the rules of[ using GITHUB ISSUES in the project.](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

 If you have any other questions, make sure you provide a **Minimal, Reproducible Example - with HelloController** that explains what you want to do.
