### ISSUE TITLE
How to make it working with @RestController annotated webflux app?

### ISSUE THREAD

**Issue by rainmanhhh** [springdoc/springdoc-openapi#1147]
I got this error
```
Caused by: java.lang.NoClassDefFoundError: javax.servlet.http.HttpServletRequest
	at java.base/java.lang.Class.getDeclaredMethodsImpl(Native Method) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:1137) ~[na:na]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:463) ~[spring-core-5.3.6.jar:5.3.6]
	... 47 common frames omitted
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpServletRequest
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:792) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:1108) ~[na:na]
	... 50 common frames omitted
```

https://springdoc.org/#spring-webfluxwebmvc-fn-with-functional-endpoints only shows functional-endpoints config, what about traditional annotated controllers?

**Comment by bnasslahsen** [comment]
read the documentation well.
Use https://springdoc.org/#spring-webflux-support

**Comment by bnasslahsen** [comment]
read rules for [Using GitHub Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
