### ISSUE TITLE
NullPointerException on calling GET /v3/api-docs

### ISSUE THREAD

**Issue by MugdhaB** [springdoc/springdoc-openapi#142]
I used 1.2.3 with a small demo springboot application and I could get openapi doc using springdoc-openapi. 

But when I try the same with our product I get following error on calling GET /v3/api-docs

java.lang.NullPointerException: null
        at org.springdoc.core.AbstractParameterBuilder.calculateSchema(AbstractParameterBuilder.java:173)
        at org.springdoc.core.AbstractRequestBuilder.buildParam(AbstractRequestBuilder.java:215)
        at org.springdoc.core.AbstractRequestBuilder.buildParam(AbstractRequestBuilder.java:187)
        at org.springdoc.core.AbstractRequestBuilder.buildParams(AbstractRequestBuilder.java:159)
        at org.springdoc.core.AbstractRequestBuilder.build(AbstractRequestBuilder.java:91)
        at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:155)
        at org.springdoc.api.OpenApiResource.calculatePath(OpenApiResource.java:99)
        at org.springdoc.api.OpenApiResource.getPaths(OpenApiResource.java:81)
        at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:77)
        at org.springdoc.api.OpenApiResource.openapiJson(OpenApiResource.java:65)

**Comment by springdoc** [comment]
Hi, 

 Your description shows the line of code where the problem resides.
 Can you please add a sample HelloController, with the single method, that caused the issue, so the fix can be more accurate?

**Comment by springdoc** [comment]
This exception should not occur with v1.2.4 of springdoc-openapi.
It would be nice, if you can provide the sample to reproduce the issue, in order to make sure the fix works as expected.
