### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/servlet/ServletException in Full webFlux project

### ISSUE THREAD

**Issue by wizaord** [springdoc/springdoc-openapi#1426]
Hi

I think there is an issue with the class **GenericResponseService** presents in the package **org.springdoc.core**.

I have a project with the dependency
```
<dependency>
       <groupId>org.springdoc</groupId>
       <artifactId>springdoc-openapi-webflux-ui</artifactId>
       <version>1.6.4</version>
</dependency>
```

I let the default configuration.
But when the application starts, I have the following exception : 

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.core.GenericResponseService]: Factory method 'responseBuilder' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/ServletException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.13.jar:5.3.13]
	... 105 common frames omitted
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletException
	at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[na:na]
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[na:na]
```

In the code, we see that the class **SpringDocWebFluxConfiguration** executes this code 

```
@Bean
    @ConditionalOnMissingBean
    GenericResponseService responseBuilder(OperationService operationService, List<ReturnTypeParser> returnTypeParsers, SpringDocConfigProperties springDocConfigProperties, PropertyResolverUtils propertyResolverUtils) {
        return new GenericResponseService(operationService, returnTypeParsers, springDocConfigProperties, propertyResolverUtils);
    }
```

And in the GenericResponseService, there is the following static code : 

```
static {
        try {
            responseEntityExceptionHandlerClass = Class.forName("org.springframework.web.servlet.mvc.method.annotation.ResponseEntityExceptionHandler");
        } catch (ClassNotFoundException var1) {
            LOGGER.trace(var1.getMessage());
        }

    }
```

It cannot work in a webFlux project because I think that this dependency is only in a "web" project.

**Comment by bnasslahsen** [comment]
@wizaord, 

There is no issue.
The code portion you are pointing out is just with logging in **trace level** that you can disable.

If you believe, you are facing an issue, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, and can be reopened if any relevant information is provided.
