### ISSUE TITLE
Misleading exception

### ISSUE THREAD

**Issue by NaimadTheOne** [springdoc/springdoc-openapi#1460]
**Describe the bug**
- When create empty annotation @Schema on class following misleading runtime exception is throw:
java.lang.NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.enumAsRef()Z
	at io.swagger.v3.core.util.AnnotationsUtils.hasSchemaAnnotation(AnnotationsUtils.java:99)
	at io.swagger.v3.core.util.AnnotationsUtils.mergeSchemaAnnotations(AnnotationsUtils.java:1333)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:143)
	at org.springdoc.core.converters.PageableOpenAPIConverter.resolve(PageableOpenAPIConverter.java:75)
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:123)
	at org.springdoc.core.converters.PropertyCustomizingConverter.resolve(PropertyCustomizingConverter.java:56)
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:50)
	at org.springdoc.core.converters.ResponseSupportConverter.resolve(ResponseSupportConverter.java:61)
	at org.springdoc.core.converters.SchemaPropertyDeprecatingConverter.resolve(SchemaPropertyDeprecatingConverter.java:55)
	at org.springdoc.core.converters.PolymorphicModelConverter.resolve(PolymorphicModelConverter.java:46)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:97)
	at io.swagger.v3.core.converter.ModelConverters.resolveAsResolvedSchema(ModelConverters.java:117)
	at org.springdoc.core.SpringDocAnnotationsUtils.extractSchema(SpringDocAnnotationsUtils.java:116)
	at org.springdoc.core.GenericParameterService.calculateSchema(GenericParameterService.java:321)
	at org.springdoc.core.AbstractRequestService.buildParam(AbstractRequestService.java:488)
	at org.springdoc.core.AbstractRequestService.buildParams(AbstractRequestService.java:446)
	at org.springdoc.core.AbstractRequestService.build(AbstractRequestService.java:267)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:457)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:604)
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:215)
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:162)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:323)
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:123)
	at org.springdoc.webmvc.api.OpenApiWebMvcResource.openapiJson(OpenApiWebMvcResource.java:107)
	at org.springdoc.webmvc.api.OpenApiWebMvcResource$$FastClassBySpringCGLIB$$1f5c1b95.invoke(<generated>)

**To Reproduce**
- What version of spring-boot you are using? version 2.6
- What modules and versions of springdoc-openapi are you using? version 1.6.4

**Expected behavior**
- Error should not be throw. If field description is required remove default value ""

**Screenshots**
![image](https://user-images.githubusercontent.com/33543835/150588880-8175d196-beed-4919-b20f-4d2d9311a627.png)

**Comment by bnasslahsen** [comment]
@NaimadTheOne, 

The problem is you code dependencies.
If you believe you are facing an issue, make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by NaimadTheOne** [comment]
I can confirm that in simple app with HelloController this error can be reproduced.

Could you give me a hint what projects dependencies can cause this kind of problem?

**Comment by bnasslahsen** [comment]
If you believe you are facing an issue, make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
