### ISSUE TITLE
NullPointerException for interface methods

### ISSUE THREAD

**Issue by strmer15** [springdoc/springdoc-openapi#147]
If I use an interface for OpenAPI annotations, a NullPointerException is thrown for methods that are not set as default:

```
Caused by: java.lang.NullPointerException: null
        at org.springdoc.core.AbstractRequestBuilder.build(AbstractRequestBuilder.java:72) ~[springdoc-openapi-common-1.2.4.jar!/:na]
        at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:155) ~[springdoc-openapi-common-1.2.4.jar!/:na]
        at org.springdoc.api.OpenApiResource.calculatePath(OpenApiResource.java:99) ~[springdoc-openapi-webmvc-core-1.2.4.jar!/:na]
        at org.springdoc.api.OpenApiResource.getPaths(OpenApiResource.java:81) ~[springdoc-openapi-webmvc-core-1.2.4.jar!/:na]
        at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:77) ~[springdoc-openapi-common-1.2.4.jar!/:na]
        at org.springdoc.api.OpenApiResource.openapiJson(OpenApiResource.java:65) ~[springdoc-openapi-webmvc-core-1.2.4.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
```
I'm using JDK 11 with -parameter and -g:source,lines,vars to compile my code.  When I run the debugger, the `pNames` variable in the class is null, since Spring's `ParameterNameDiscoverer` can't find the parameter names on the interface methods.  However, the `parameters` array found through reflection does have all of the names, so you should check if `pNames` is null and then use the `parameters` array instead to get the names if so.

**Comment by springdoc** [comment]
To be more efficient of addressing your issue, could you please add a sample code describing how to reproduce your issue?
