### ISSUE TITLE
ClassNotFoundException: OpenApiMethodFilter (1.6.5 regression)

### ISSUE THREAD

**Issue by ITman1** [springdoc/springdoc-openapi#1477]
**Describe the bug**
Last library version 1.6.5 contains regression in webflux starter - application is unable to start. 
Most likely caused by this PR: https://github.com/springdoc/springdoc-openapi/pull/1429
Older version 1.6.4 works fine.

```
Caused by: java.lang.ClassNotFoundException: org.springdoc.core.filters.OpenApiMethodFilter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
	at java.base/java.lang.Class.forName(Class.java:467) ~[na:na]
	at java.base/sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114) ~[na:na]
	... 38 common frames omitted
```

**To Reproduce**
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.6.5</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
```

**Comment by bnasslahsen** [comment]
@ITman1, 

Not reproducible [using the demos](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux).
Please provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

**Comment by ITman1** [comment]
You are right, after IDEA restart works like a charm, some nasty caches... Sorry for confusion... 😞
