### ISSUE TITLE
Could not resolve view with name 'redirect:/swagger-ui/index.html?url=/v3/api-docs&validatorUrl='

### ISSUE THREAD

**Issue by Aloren** [springdoc/springdoc-openapi#150]
Hello, guys!
First of all I would like to thank you for the library :)
I'm currently researching it as a replacement for springfox swagger as it is not maintained anymore and I have found the following issue.

When opening http://localhost:8080/swagger-ui.html
I get:
```
2019-11-08 12:51:31.774 ERROR 26637 --- [nio-8080-exec-7] o.a.c.c.C.[.[.[.[dispatcherServlet]      : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Could not resolve view with name 'redirect:/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=' in servlet with name 'dispatcherServlet'] with root cause

javax.servlet.ServletException: Could not resolve view with name 'redirect:/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=' in servlet with name 'dispatcherServlet'
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1351) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1117) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1056) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:897) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882) ~[spring-webmvc-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90) ~[spring-boot-actuator-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.springframework.cloud.sleuth.instrument.web.ExceptionLoggingFilter.doFilter(ExceptionLoggingFilter.java:50) ~[spring-cloud-sleuth-core-2.1.1.RELEASE.jar:2.1.1.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at brave.servlet.TracingFilter.doFilter(TracingFilter.java:86) ~[brave-instrumentation-servlet-5.6.1.jar:?]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117) ~[spring-boot-actuator-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106) ~[spring-boot-actuator-2.1.5.RELEASE.jar:2.1.5.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.1.7.RELEASE.jar:5.1.7.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:200) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:836) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1747) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-embed-core-9.0.19.jar:9.0.19]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```

When opening http://localhost:8080/swagger-ui/index.html?url=/v3/api-docs directly -- everything works fine.
Any ideas?

**Comment by springdoc** [comment]
Hello, 

 We would be so happy to help, if you can attach or add the reference to a sample code that helps reproducing the issue you are describing.

**Comment by Aloren** [comment]
I’ve managed to resolve the issue. I haven’t yet exactly found what was the issue — it was either with @EnableWebMvc annotation or resource handler. I will investigate that in more detail and post the solution as soon as I have more time.

**Comment by aaron-hooper** [comment]
> I’ve managed to resolve the issue. I haven’t yet exactly found what was the issue — it was either with @EnableWebMvc annotation or resource handler. I will investigate that in more detail and post the solution as soon as I have more time.

Any update on what the issue was? I'm running into a similar issue except going directly to  http://localhost:8080/swagger-ui/index.html?url=/v3/api-docs returns a 404.

**Comment by andygoossens** [comment]
`@EnableWebMvc` seems to be the culprit.

To reproduce:
* checkout https://github.com/springdoc/springdoc-openapi-demos
* add `@EnableWebMvc` on class `org.springdoc.demo.app1.Application`
* run `org.springdoc.demo.app1.Application`
* visit http://localhost:8080/swagger-ui.html

**Comment by tonyfalabella** [comment]
I have the same issue as @aaron-hooper 

> I'm running into a similar issue except going directly to http://localhost:8080/swagger-ui/index.html?url=/v3/api-docs returns a 404.

I've tried with version 1.2.18 and 1.2.22 - same issue.  I've also attempted to create my own `SwaggerConfig` class in version 1.2.18 without the `@EnableWebMvc` and done what I think are the proper overrides in my main class but still with no luck.
```
@SpringBootApplication(exclude = {org.springdoc.config.SpringDocConfiguration.class})
@Configuration
@EnableConfigurationProperties
@ComponentScan(
    basePackages = {"org.springdoc", "com.jpmorgan.grt", "com.jpmorgan.bmt"},
    excludeFilters = {
      @ComponentScan.Filter(
          type = FilterType.ASSIGNABLE_TYPE,
          classes = {SwaggerConfig.class, SpringDocConfiguration.class}),
    })
public class MyApplication {
```

**Comment by Aloren** [comment]
@tonyfalabella can you provide a sample project with this issue? So that we could take a look at it.

**Comment by tonyfalabella** [comment]
Sorry just getting back to this.  No issue with the lib - issue for me was when I was running locally in IntelliJ.

If you get a 404 error when Spring redirects swagger-ui.html to the webjar resource (that page resides in the webjars.jar file you included in your pom.xml) most likely you asked IntelliJ to "shorten your classpath".  
If you're on Java < 9 IntelliJ offers "JAR manifest" and "classpath file" options to shorten the classpath.  The "JAR manifest" will give the 404 error but the "classpath file" works.

If you're on Java 11 the "classpath file" option is not available but "@argFile" is available.   Unfortunately that didn't work for me.  The only fix I could get to work was to move my Maven repos to a dir that was shorter.

**Comment by Samyssmile** [comment]
I had same Issue, as I understand @EnableWebMvc is not needed in Spring Boot 2.2.4. I removed it, and everything works now as expected.

**Comment by joostpapendorp** [comment]
Hi guys!

I had another variant of the same cause, so for future debuggers:

WebMvc was in the way, but in stead of @EnableWebMvc, our project used DelegatingWebMvcConfiguration. Refactoring this solved the problem.

Cheers!
 Joost

**Comment by cvinicius987** [comment]
> I had same Issue, as I understand @EnableWebMvc is not needed in Spring Boot 2.2.4. I removed it, and everything works now as expected.

I had the same issue in Spring Boot 2.3.0, I resolved when I removed the @EnableWebMvc too, thank you.

**Comment by ghsatpute** [comment]
@joostpapendorp 's comment does give some pointer but doesn't explain how to refactor. 

I didn't have `@EnableWebMvc` but I had used `WebMvcConfigurationSupport`. I used `WebMvcConfigurer` instead and that solve the problem.
