### ISSUE TITLE
[springdoc-openapi-native] NullPointerException due to missing TypeHint in v1.6.6+

### ISSUE THREAD

**Issue by tnaskali** [springdoc/springdoc-openapi#1604]
**Describe the bug**
Starting from v1.6.6 I'm experiencing a NullPointerException when accessing the swagger-ui.html page in a native executable.

```
java.lang.NullPointerException: null
	at org.springdoc.core.DelegatingMethodParameter.changeContainingClass(DelegatingMethodParameter.java:265) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException:
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.AuthorizationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authorization.ExceptionTranslationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.logout.LogoutWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.savedrequest.ServerRequestCacheWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.SecurityContextServerWebExchangeWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.authentication.AuthenticationWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.context.ReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.header.HttpHeaderWriterWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.config.web.server.ServerHttpSecurity$ServerWebExchangeReactorContextWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.security.web.server.WebFilterChainProxy [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/bgg-api/v3/api-docs/v1" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springdoc.core.DelegatingMethodParameter.changeContainingClass(DelegatingMethodParameter.java:265) ~[na:na]
		at org.springdoc.core.MethodParameterPojoExtractor.lambda$fromSimpleClass$4(MethodParameterPojoExtractor.java:178) ~[na:na]
		at org.springdoc.core.MethodParameterPojoExtractor$$Lambda$b97f72e6396e83fbc0372ee324c698984670715f.apply(Unknown Source) ~[na:na]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
		at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
		at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:na]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[bgg-api:na]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[bgg-api:na]
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[bgg-api:na]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[bgg-api:na]
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[bgg-api:na]
		at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274) ~[na:na]
		at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177) ~[na:na]
		at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[na:na]
		at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[bgg-api:na]
		at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[bgg-api:na]
		at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[bgg-api:na]
		at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
		at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[bgg-api:na]
		at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[bgg-api:na]
		at org.springdoc.core.DelegatingMethodParameter.customize(DelegatingMethodParameter.java:119) ~[na:na]
		at org.springdoc.core.AbstractRequestService.build(AbstractRequestService.java:237) ~[bgg-api:1.6.7]
		at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:457) ~[bgg-api:1.6.7]
		at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:604) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiResource.lambda$calculatePath$4(OpenApiResource.java:200) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiResource$$Lambda$d41ec50750c06a5605b688ef9f2b1b59b4dd6fe8.accept(Unknown Source) ~[na:na]
		at java.util.Optional.ifPresent(Optional.java:183) ~[bgg-api:na]
		at org.springdoc.webflux.api.OpenApiResource.calculatePath(OpenApiResource.java:183) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiResource.lambda$getPaths$0(OpenApiResource.java:167) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiResource$$Lambda$8e078c489305da74751a1c7c8966e22543ff5318.accept(Unknown Source) ~[na:na]
		at java.util.Optional.ifPresent(Optional.java:183) ~[bgg-api:na]
		at org.springdoc.webflux.api.OpenApiResource.getPaths(OpenApiResource.java:159) ~[bgg-api:1.6.7]
		at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:323) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiResource.openapiJson(OpenApiResource.java:129) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.OpenApiWebfluxResource.openapiJson(OpenApiWebfluxResource.java:112) ~[bgg-api:1.6.7]
		at org.springdoc.webflux.api.MultipleOpenApiWebFluxResource.openapiJson(MultipleOpenApiWebFluxResource.java:85) ~[bgg-api:1.6.7]
		at java.lang.reflect.Method.invoke(Method.java:566) ~[bgg-api:na]
		at org.springframework.web.reactive.result.method.InvocableHandlerMethod.lambda$invoke$0(InvocableHandlerMethod.java:144) ~[na:na]
		at org.springframework.web.reactive.result.method.InvocableHandlerMethod$$Lambda$2ef91283da822d592df577b86b677020a99ccabe.apply(Unknown Source) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:125) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:251) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:336) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
		at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:325) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) ~[na:na]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators.complete(Operators.java:137) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:120) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[na:na]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152) ~[na:na]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onComplete(MonoPeekTerminal.java:299) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:148) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onNext(FluxFilter.java:113) ~[na:na]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:101) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863) ~[na:na]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127) ~[na:na]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onNext(FluxFilterFuseable.java:118) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.request(FluxFilterFuseable.java:191) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onSubscribe(MonoFlatMap.java:110) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96) ~[na:na]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableSubscriber.onSubscribe(FluxFilterFuseable.java:87) ~[na:na]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[na:na]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166) ~[na:na]
		at reactor.core.publisher.FluxPeekFuseable$PeekConditionalSubscriber.onComplete(FluxPeekFuseable.java:940) ~[na:na]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:85) ~[na:na]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2194) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2068) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:82) ~[na:na]
		at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166) ~[na:na]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:846) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:608) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:588) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:465) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onComplete(FluxPeekFuseable.java:277) ~[na:na]
		at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:294) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.request(FluxPeekFuseable.java:144) ~[na:na]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onSubscribe(FluxPeekFuseable.java:178) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165) ~[na:na]
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157) ~[bgg-api:3.4.16]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onComplete(FluxDefaultIfEmpty.java:109) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:142) ~[na:na]
		at reactor.core.publisher.FluxFilter$FilterSubscriber.onComplete(FluxFilter.java:166) ~[na:na]
		at reactor.core.publisher.FluxMap$MapConditionalSubscriber.onComplete(FluxMap.java:269) ~[na:na]
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1817) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.signalCached(MonoCacheTime.java:337) ~[bgg-api:3.4.16]
		at reactor.core.publisher.MonoCacheTime$CoordinatorSubscriber.onNext(MonoCacheTime.java:354) ~[bgg-api:3.4.16]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:200) ~[na:na]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onNext(FluxPeekFuseable.java:210) ~[na:na]
		at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180) ~[na:na]
		at reactor.core.publisher.MonoPublishOn$PublishOnSubscriber.run(MonoPublishOn.java:181) ~[bgg-api:3.4.16]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[bgg-api:3.4.16]
		at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[bgg-api:3.4.16]
		at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[bgg-api:na]
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[bgg-api:na]
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
		at java.lang.Thread.run(Thread.java:829) ~[bgg-api:na]
		at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704) ~[bgg-api:na]
		at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202) ~[na:na]
```

**To Reproduce**
My configuration:
- Mac mini M1
- spring-boot-2.6.6
- springdoc-openapi-1.6.6+

- checkout https://github.com/tnaskali/bgg-api/tree/develop and update property org.springdoc.springdoc-openapi.version to version 1.6.6 or 1.6.7 in pom.xml
- run `mvn clean package -Pnative -DskipTests`
- run `/target/bgg-api`
- navigate to http://localhost:8088/bgg-api/swagger-ui.html
- error message in the UI ("Failed to load API definition") and NPE in the logs

**Expected behavior**
- standard Swagger UI behaviour

**Additional context**
probably introduced in 3061086
https://github.com/springdoc/springdoc-openapi/blob/b7380a6d3b6afafc19bc96abbd43e33d760740d8/springdoc-openapi-common/src/main/java/org/springdoc/core/DelegatingMethodParameter.java#L264
https://github.com/springdoc/springdoc-openapi/blob/b7380a6d3b6afafc19bc96abbd43e33d760740d8/springdoc-openapi-common/src/main/java/org/springdoc/core/DelegatingMethodParameter.java#L266

**Comment by tnaskali** [comment]
adding a TypeHint for org.springframework.core.MethodParameter fixes the issue
