### ISSUE TITLE
Compatibility with Spring Boot 3.0 M3 / Spring Framework 6.0 M4

### ISSUE THREAD

**Issue by goafabric** [springdoc/springdoc-openapi#1671]
While version 2.0.0-M2 worked nicely until Spring Boot 3.0 M2.
It's not working any more with M3.
The problem seems to be a breaking change inside the Spring Framework itself.
HttpStatus was previously just a simple enum and is now somehow intermingled with the new java 17 sealed (interfaces) feature.
As no reflection is involved here, it might be enough to recompile springdoc with the new spring framework 6.0 M4 deps.

Which might of course break compatibility with all lower versions...

--- cut ---

Caused by: java.lang.NoSuchMethodError: 'org.springframework.http.ResponseEntity$BodyBuilder org.springframework.http.ResponseEntity.status(org.springframework.http.HttpStatus)'
	at org.springdoc.webmvc.ui.SwaggerWelcomeCommon.redirectToUi(SwaggerWelcomeCommon.java:69) ~[springdoc-openapi-starter-webmvc-ui-2.0.0-M2.jar:2.0.0-M2]
	at org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc.redirectToUi(SwaggerWelcomeWebMvc.java:89) ~[springdoc-openapi-starter-webmvc-ui-2.0.0-M2.jar:2.0.0-M2]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]

**Comment by bnasslahsen** [comment]
@goafabric, 

This issue, should be fixed with the latest SNAPSHOT: `2.0.0-M3-SNAPSHOT`
Don't hesitate, to let me know if there any other issues.

**Comment by goafabric** [comment]
thx

**Comment by JohnNiang** [comment]
Hi @bnasslahsen , how can I use the snapshot like below?

```groovy
implementation 'org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.0-M3-SNAPSHOT' // Cannot be downloaded
```

Or hope release `org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.0-M3` as quick as possible. Thx!

**Comment by JohnNiang** [comment]
> procedure available in the F.A.Q: https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot

Thank @bnasslahsen for providing the useful F.A.Q link!
