### ISSUE TITLE
NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.additionalProperties

### ISSUE THREAD

**Issue by urswiss** [springdoc/springdoc-openapi#1716]
**Describe the bug**
While upgrading from springdoc-openapi 1.6.6 to 1.6.9 I came across the below error:

``[INFO] 
[INFO] --- springdoc-openapi-maven-plugin:1.4:generate (default) @ ???-service ---
2022-06-22 11:14:15.575  INFO [,,] 22544 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/???/???/???]     : Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-06-22 11:14:15.575  INFO [,,] 22544 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2022-06-22 11:14:15.577  INFO [,,] 22544 --- [nio-8080-exec-1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2022-06-22 11:14:15.600  INFO [,,] 22544 --- [nio-8080-exec-1] .a.c.e.s.c.HttpRequestLoggingInterceptor : Request: [Method=GET, Uri=/??/??/??/v1/api-docs, Headers=[user-agent:"Java/11.0.9", host:"localhost:8080", accept:"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2", connection:"keep-alive"]]
2022-06-22 11:14:15.887 ERROR [,,] 22544 --- [nio-8080-exec-1] c.a.c.e.s.v.c.e.ExceptionHandlers        : Internal server error (SERVER_ERROR): Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.additionalProperties()Lio/swagger/v3/oas/annotations/media/Schema$AdditionalPropertiesValue;
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.additionalProperties()Lio/swagger/v3/oas/annotations/media/Schema$AdditionalPropertiesValue;
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.AbstractRequestLoggingFilter.doFilterInternal(AbstractRequestLoggingFilter.java:289)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.cloud.sleuth.instrument.web.servlet.TracingFilter.doFilter(TracingFilter.java:68)
	at org.springframework.cloud.sleuth.autoconfig.instrument.web.TraceWebServletConfiguration$LazyTracingFilter.doFilter(TraceWebServletConfiguration.java:131)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.springframework.cloud.sleuth.instrument.web.tomcat.TraceValve.invoke(TraceValve.java:103)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.additionalProperties()Lio/swagger/v3/oas/annotations/media/Schema$AdditionalPropertiesValue;
	at io.swagger.v3.core.util.AnnotationsUtils.hasSchemaAnnotation(AnnotationsUtils.java:101)
	at io.swagger.v3.core.util.AnnotationsUtils.getSchemaFromAnnotation(AnnotationsUtils.java:415)
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1166)
	at org.springdoc.core.GenericParameterService.setSchema(GenericParameterService.java:290)
	at org.springdoc.core.GenericParameterService.buildParameterFromDoc(GenericParameterService.java:266)
	at org.springdoc.core.AbstractRequestService.build(AbstractRequestService.java:265)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:455)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:616)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$calculatePath$10(OpenApiResource.java:228)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:210)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$getPaths$2(OpenApiResource.java:180)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:159)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:320)
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:134)
	at org.springdoc.webmvc.api.OpenApiWebMvcResource.openapiJson(OpenApiWebMvcResource.java:113)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	... 52 common frames omitted
2022-06-22 11:14:15.903  WARN [,,] 22544 --- [nio-8080-exec-1] .m.m.a.ExceptionHandlerExceptionResolver : Resolved [org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: io.swagger.v3.oas.annotations.media.Schema.additionalProperties()Lio/swagger/v3/oas/annotations/media/Schema$AdditionalPropertiesValue;]
[ERROR] An error has occured: Response code 500
``

It occurrs during generating the openapi json.

**Additional context**
Some more upgrades done (the process/system works with those):
- springdoc-openapi-maven-plugin: 1.3 -> 1.4
- openapi-generator-maven-plugin: 5.4.0 -> 6.0.0
- spring.boot: 2.6.6 -> 2.7.0
- spring.cloud: 2021.0.1 -> 2021.0.3
- mapstruct: 1.4.2 -> 1.5.2
- io.jsonwebtoken: 0.11.2 -> 0.11.5

**Comment by bnasslahsen** [comment]
@urswiss, 

Make sure you are not overriding the `swagger` jars that are shipped by springdoc.
If it's not the case, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by urswiss** [comment]
this is resolved now. There was still an old swagger dependency in the tree. Thanks for your help @bnasslahsen !
