### ISSUE TITLE
springdoc-openapi-ui 1.6.9 breaks the compatibility with Spring Boot 2.6.x

### ISSUE THREAD

**Issue by zyxist** [springdoc/springdoc-openapi#1731]
**Describe the bug**
- according to the documentation, https://springdoc.org/#what-is-the-compatibility-matrix-of-springdoc-openapi-with-spring-boot , springdoc-openapi-ui should be compatible with Spring Boot 2.6.x.
- however, it loads spring-boot 2.7.0, overwrites the version specified in the project and makes it incompatible with many other spring dependencies still in 2.6.x versions
- this causes exceptions like the one below at startup:

```
Failed to load ApplicationContext
java.lang.IllegalStateException: Failed to load ApplicationContext
	at ...
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'compositeCompatibilityVerifier' defined in class path resource [org/springframework/cloud/configuration/CompatibilityVerifierAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.configuration.CompositeCompatibilityVerifier]: Factory method 'compositeCompatibilityVerifier' threw exception; nested exception is org.springframework.cloud.configuration.CompatibilityNotMetException: Spring Cloud/ Spring Boot version compatibility checks have failed: [[VerificationResult@62584a69 description = 'Spring Boot [2.7.0] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [2.6.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn]. 
If you want to learn more about the Spring Cloud Release train compatibility, you can visit this page [https://spring.io/projects/spring-cloud#overview] and check the [Release Trains] section.
If you want to disable this check, just set the property [spring.cloud.compatibility-verifier.enabled=false]']]
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at app//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at app//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at app//org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at app//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at app//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at app//org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:136)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 107 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.cloud.configuration.CompositeCompatibilityVerifier]: Factory method 'compositeCompatibilityVerifier' threw exception; nested exception is org.springframework.cloud.configuration.CompatibilityNotMetException: Spring Cloud/ Spring Boot version compatibility checks have failed: [[VerificationResult@62584a69 description = 'Spring Boot [2.7.0] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [2.6.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn]. 
If you want to learn more about the Spring Cloud Release train compatibility, you can visit this page [https://spring.io/projects/spring-cloud#overview] and check the [Release Trains] section.
If you want to disable this check, just set the property [spring.cloud.compatibility-verifier.enabled=false]']]
	at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 126 more
Caused by: org.springframework.cloud.configuration.CompatibilityNotMetException: Spring Cloud/ Spring Boot version compatibility checks have failed: [[VerificationResult@62584a69 description = 'Spring Boot [2.7.0] is not compatible with this Spring Cloud release train', action = 'Change Spring Boot version to one of the following versions [2.6.x] .
You can find the latest Spring Boot versions here [https://spring.io/projects/spring-boot#learn]. 
If you want to learn more about the Spring Cloud Release train compatibility, you can visit this page [https://spring.io/projects/spring-cloud#overview] and check the [Release Trains] section.
If you want to disable this check, just set the property [spring.cloud.compatibility-verifier.enabled=false]']]
	at app//org.springframework.cloud.configuration.CompositeCompatibilityVerifier.verifyDependencies(CompositeCompatibilityVerifier.java:47)
	at app//org.springframework.cloud.configuration.CompatibilityVerifierAutoConfiguration.compositeCompatibilityVerifier(CompatibilityVerifierAutoConfiguration.java:44)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.1/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.1/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.1/java.lang.reflect.Method.invoke(Method.java:568)
	at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 127 more
```

**To Reproduce**
- Use springdoc-openapi-ui 1.6.9 with Spring Boot 2.6.x PLUS some other 2.6.x spring dependency.
- Compatibility verifier must not be disabled. 

**Expected behavior**
- Version 1.6.9 should continue using Spring Boot 2.6.x. To support 2.7.x you should have bumped the minor version (1.7.0) according to the compatibility matrix provided in the docs.

**Comment by iainkun** [comment]
Co-sign. I spent a good while trying to figure out why webjar resources were not being found when deployed, and changing nothing else besides downgrading `springdoc-openapi-ui` to `1.6.8` solved my issue.

**Comment by bnasslahsen** [comment]
@zyxist, 

Not reproducible.
If you believe you faced a bug, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by zyxist** [comment]
Use the following `build.gradle`:

```
buildscript {
	dependencies {
		classpath "io.spring.gradle:dependency-management-plugin:1.0.10.RELEASE"
	}
}

plugins {
	id 'io.spring.dependency-management' version '1.0.12.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
	mavenCentral()
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.3"
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web:2.6.10'
	implementation 'org.springframework.boot:spring-boot-starter-actuator:2.6.10'
	implementation 'org.springframework.cloud:spring-cloud-starter-bootstrap:3.1.3'
	implementation 'org.springdoc:springdoc-openapi-ui:1.6.9'

	testImplementation 'org.springframework.boot:spring-boot-starter-test:2.6.10'
}

tasks.named('test') {
	useJUnitPlatform()
}
dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

tasks.named('test') {
	useJUnitPlatform()
}
```

and `application.properties`:

```
spring.cloud.compatibility-verifier.enabled=true
spring.cloud.compatibility-verifier.compatible-boot-versions=2.6
```

`SampleController.java`:

```
@RestController
public class SampleController {
    @Operation(summary = "test")
    @GetMapping("/test")
    public String test() {
        return "test";
    }
}
```

I tested it and it reproduces the problem. Using `springdoc-openapi-ui` in this setup changes the Spring Boot version to 2.7.0 under the hood, and it is captured by the compatibility verifier. At the same time, many dependencies still remain at 2.6.10 version, which may cause hard-to-capture-issues. The problem does not appear, when one uses Spring Boot Gradle Plugin which appears to enforce single version.

Some context:
 - sometimes you can't just use the plugin. In our case, we have opinionated wrapper around Spring which does the version magic and other stuff for us, and using plugin is not a solution for us,
 - we had a couple of issues with dependency version mismatch, and the compatibility verifier allows capturing such errors early, before they cause problems.

The root cause is that the library uses spring-boot-starter-parent:2.7.0 in the POM file: https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/pom.xml whereas it should use 2.6.10. 

I'd expect that if the project claims minor version compatiblity 1.6 <-> 2.6, it should depend exactly on this framework version.

**Comment by zyxist** [comment]
@bnasslahsen : could you comment on the provided reproduction example? Is it okay now? It should reproduce the issue now, and I also noted the actual place in pom.xml file which causes the issue.

**Comment by bnasslahsen** [comment]
@bnasslahsen,

View my answer in #1776 and do not create duplicates next time. 
Update, one single ticket. And if your update is relevant, the ticket will be reopened.
