### ISSUE TITLE
Add support for Spring Native 0.12.1

### ISSUE THREAD

**Issue by magnus-larsson** [springdoc/springdoc-openapi#1746]
**Describe the bug**
The demo project [springdoc-openapi-spring-boot-2-webflux](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux) runs fine with Spring Boot 2.6.7 and Spring Native 0.11.5 but fails to create a native image when upgraded to Spring Boot 2.7.1 and Spring Native 0.12.1.

**To Reproduce**

1. Check out the demo project:2. 

   ```
   git clone git@github.com:springdoc/springdoc-openapi-demos.git
   cd springdoc-openapi-spring-boot-2-webflux
   ```

3. Build and run with Java VM

   ```
   mvn clean package
   java -jar target/springdoc-openapi-spring-boot-2-webflux-3.1.6-SNAPSHOT.jar
   ```

   Starts up as expected.

4. Build and run native image

   ```
   mvn -Pnative clean package 
   target/springdoc-openapi-spring-boot-2-webflux 
   ```

   Starts up as expected.

5. Upgrade to Spring Boot 2.7.1, Spring Native 0.12.1, and Spring Cloud 2021.0.3.5. 

   Apply the following changes in `springdoc-openapi-demos/pom.xml`:

   ```
   <spring-boot.version>2.7.1</spring-boot.version>
   <spring-native.version>0.12.1</spring-native.version>
   <spring-cloud.version>2021.0.3</spring-cloud.version>
   ```

6. Build and run with Java VM and Spring Boot 2.7.1

   ```
   mvn clean package
   java -jar target/springdoc-openapi-spring-boot-2-webflux-3.1.6-SNAPSHOT.jar
   ```

   Starts up as expected.

7. Build and run native image with Spring Native 0.12.1 

   ```
   mvn -Pnative clean package 
   ```

   Stops with the error:

   ```
   2022-07-21 13:23:16.884  INFO 72086 --- [           main] o.s.nativex.support.SpringAnalyzer       : Spring Native operating mode: native
   2022-07-21 13:23:19.971  INFO 72086 --- [           main] o.s.aop.framework.ProxyGenerator         : Generating class file bytes for a proxy named  org.springdoc.demo.app3.repository.TweetRepository$$SpringProxy$688f3be5
   Exception in thread "main" java.lang.AbstractMethodError: Receiver class org.springframework.aop.framework.ProxyGenerator$AuxiliaryTypeNamingStrategy does not define or inherit an implementation of the resolved method 'abstract java.lang.String name(net.bytebuddy.description.type.TypeDescription, net.bytebuddy.implementation.auxiliary.AuxiliaryType)' of interface net.bytebuddy.implementation.auxiliary.AuxiliaryType$NamingStrategy.
        at net.bytebuddy.implementation.Implementation$Context$Default.register(Implementation.java:888)
        at net.bytebuddy.implementation.auxiliary.MethodCallProxy$AssignableSignatureCall.apply(MethodCallProxy.java:460)
        at net.bytebuddy.implementation.bind.MethodDelegationBinder$ParameterBinding$Anonymous.apply(MethodDelegationBinder.java:258)
        at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:243)
        at net.bytebuddy.implementation.bind.MethodDelegationBinder$MethodBinding$Builder$Build.apply(MethodDelegationBinder.java:564)
        at net.bytebuddy.implementation.bytecode.StackManipulation$Compound.apply(StackManipulation.java:243)
        at net.bytebuddy.implementation.MethodDelegation$Appender.apply(MethodDelegation.java:1345)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyCode(TypeWriter.java:719)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod$WithBody.applyBody(TypeWriter.java:704)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$MethodPool$Record$ForDefinedMethod.apply(TypeWriter.java:611)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default$ForCreation.create(TypeWriter.java:5959)
        at net.bytebuddy.dynamic.scaffold.TypeWriter$Default.make(TypeWriter.java:2213)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:232)
        at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.make(SubclassDynamicTypeBuilder.java:204)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3668)
        at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3906)
        at org.springframework.aop.framework.ProxyGenerator.getProxyBytes(ProxyGenerator.java:94)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxy(ConfigurationContributor.java:200)
        at org.springframework.aot.nativex.ConfigurationContributor.generateBuildTimeClassProxies(ConfigurationContributor.java:177)
        at org.springframework.aot.nativex.ConfigurationContributor.processBuildTimeClassProxyRequests(ConfigurationContributor.java:142)
        at org.springframework.aot.nativex.ConfigurationContributor.contribute(ConfigurationContributor.java:74)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:91)
        at org.springframework.aot.build.BootstrapCodeGenerator.generate(BootstrapCodeGenerator.java:71)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:107)
        at org.springframework.aot.build.GenerateBootstrapCommand.call(GenerateBootstrapCommand.java:42)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.springframework.aot.build.GenerateBootstrapCommand.main(GenerateBootstrapCommand.java:112)
   ```

**Expected behavior**
The native compile command using Spring Native 0.12.1 produces a native image in the same way as when used with Spring Native 0.11.5.

**Additional context**
I have noticed that the [documentation regarding Spring Native support](https://springdoc.org/#spring-native-support) does not yet mention v0.12.1.

**Comment by bnasslahsen** [comment]
@magnus-larsson,

Support Added with this commit 40a643711186ba9fb0b55ccb1de29fa1c7cee88c

Tested using:
- GraalVM CE 22.1.0
- Spring-native 0.12.1
- springdoc-openapi 1.6.10-SNAPSHOT

**Comment by magnus-larsson** [comment]
**@bnasslahsen,** 

Thanks, great news!

I will try out springdoc-openapi 1.6.10-SNAPSHOT later this week and create new issues if I run into any new problems with Spring-native 0.12.1 (I'm currently traveling)

**Comment by magnus-larsson** [comment]
@bnasslahsen: I think I have found an issue with springdoc-openapi 1.6.10-SNAPSHOT, when using the GraalVM tracing agent to create a configuration for the GraalVM native compiler, see #1781.
