### ISSUE TITLE
Version 1.6.9 breaks compatibility with Swagger v3

### ISSUE THREAD

**Issue by jbx1** [springdoc/springdoc-openapi#1747]
I am using Springdoc Open API with Spring Boot 2.7.1 with an Open API (Swagger v3) definition. 
All works fine up to version 1.6.8. Upgrading to version 1.6.9 breaks when trying to access the documentation page exposed by the service.

The exception is the following.

```
java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)'
	at org.springdoc.core.RequestBodyInfo.addProperties(RequestBodyInfo.java:91) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
	at org.springdoc.core.GenericParameterService.calculateRequestBodySchema(GenericParameterService.java:381) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
	at org.springdoc.core.GenericParameterService.calculateSchema(GenericParameterService.java:343) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
	at org.springdoc.core.RequestBodyService.buildRequestBody(RequestBodyService.java:275) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
	at org.springdoc.core.RequestBodyService.calculateRequestBodyInfo(RequestBodyService.java:251) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
...
```

Downgrading back to v1.6.8 fixes the issue.

Other version information:

org.openapitools.openapi-generator-maven-plugin: 5.3.0
io.swagger.parser.v3.swagger-parser: 2.0.29

**Comment by amseager** [comment]
Same thing, have Spring Boot 2.7.2 and openapi generator 5.3.0.
Downgrading to 1.6.8 solved the problem.

**Comment by bnasslahsen** [comment]
@jbx1 and @amseager your configuration is certainly wrong. Just, review your project dependencies.
You shouldn't change swagger-core `2.2.1` version that is shipped by `springdoc-openapi`...

**Comment by jiangfengji** [comment]
great!
