### ISSUE TITLE
Duplicated mapping key. Random ConcurrentModificationException error

### ISSUE THREAD

**Issue by mbedna** [springdoc/springdoc-openapi#206]
Hello,
I get ConcurrentModificationException after deloying application. Problem is that this happens randomly. After redeploy documentation usually starts working. Message which is visible in swagger:

> Parser error 

> duplicated mapping key

Springdoc:  1.2.13.
Spring boot: 2.2.1 
Do you have any idea how to solve this?

`java.util.ConcurrentModificationException: null
	at java.base/java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
	at java.base/java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:746)
	at org.springdoc.core.OperationBuilder.existOperationId(OperationBuilder.java:210)
	at org.springdoc.core.OperationBuilder.getOperationId(OperationBuilder.java:195)
	at org.springdoc.core.OperationBuilder.getOperationId(OperationBuilder.java:366)
	at org.springdoc.core.AbstractRequestBuilder.build(AbstractRequestBuilder.java:48)
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:143)
	at org.springdoc.api.OpenApiResource.calculatePath(OpenApiResource.java:96)
	at org.springdoc.api.OpenApiResource.getPaths(OpenApiResource.java:76)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:63)
	at org.springdoc.api.OpenApiResource.openapiJson(OpenApiResource.java:59)`

**Comment by springdoc** [comment]
Hi, 

 We are unable to reproduce this issue. 
 We have replaced the loop using iterator. This fix will be available on v1.2.14 of springdoc-openapi.
 If it doesn't fix the issue, please add a sample code to reproduce it.
