### ISSUE TITLE
Upgrade to Spring Boot 3.0.3 breaks AOT support

### ISSUE THREAD

**Issue by goafabric** [springdoc/springdoc-openapi#2097]
A Simple Spring Boot Project with 
- OpenAPI 2.x + 
- Spring Web
- NO Hibernate / JPA

Breaks within the AOT Phase when Upgrading to Boot 3.0.3, see Exception Below.
This can be solved by adding "org.springframework.boot:spring-boot-starter-validation" which is not required by the Project however.

I guess Spring made some changes in the AOT processing that now conflict with SpringDoc.
(e.g. detecting Validation Annotations and throwing an Exception if no Provider is there)

Maybe you can take a look, like you did in the past when Spring Upgrades broke.

Thanx 

`Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.springframework.validation.beanvalidation.BeanValidationBeanRegistrationAotProcessor.processAheadOfTime(BeanValidationBeanRegistrationAotProcessor.java:59)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getAotContributions(BeanDefinitionMethodGeneratorFactory.java:151)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:99)
	at org.springframework.beans.factory.aot.BeanDefinitionMethodGeneratorFactory.getBeanDefinitionMethodGenerator(BeanDefinitionMethodGeneratorFactory.java:115)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:48)
	at org.springframework.beans.factory.aot.BeanRegistrationsAotProcessor.processAheadOfTime(BeanRegistrationsAotProcessor.java:36)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.getContributions(BeanFactoryInitializationAotContributions.java:67)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:49)
	at org.springframework.context.aot.BeanFactoryInitializationAotContributions.<init>(BeanFactoryInitializationAotContributions.java:44)
	at org.springframework.context.aot.ApplicationContextAotGenerator.lambda$processAheadOfTime$0(ApplicationContextAotGenerator.java:58)
	at org.springframework.context.aot.ApplicationContextAotGenerator.withCglibClassHandler(ApplicationContextAotGenerator.java:67)
	at org.springframework.context.aot.ApplicationContextAotGenerator.processAheadOfTime(ApplicationContextAotGenerator.java:53)
	at org.springframework.context.aot.ContextAotProcessor.performAotProcessing(ContextAotProcessor.java:106)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:84)
	at org.springframework.context.aot.ContextAotProcessor.doProcess(ContextAotProcessor.java:49)
	at org.springframework.context.aot.AbstractAotProcessor.process(AbstractAotProcessor.java:82)
	at org.springframework.boot.SpringApplicationAotProcessor.main(SpringApplicationAotProcessor.java:80)
Caused by: jakarta.validation.NoProviderFoundException: Unable to create a Configuration, because no Jakarta Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath.
	at jakarta.validation.Validation$GenericBootstrapImpl.configure(Validation.java:291)
	at jakarta.validation.Validation.buildDefaultValidatorFactory(Validation.java:103)
	at org.springframework.validation.beanvalidation.BeanValidationBeanRegistrationAotProcessor$BeanValidationDelegate.<clinit>(BeanValidationBeanRegistrationAotProcessor.java:66)
	... 17 more`

**Comment by bnasslahsen** [comment]
@goafabric,

i have just tested Native build with the latest demos for v2 without any issues:

Clone the demos repositort:
- https://github.com/springdoc/springdoc-openapi-demos/tree/2.x

Go to either webmc or webflux demo: `cd demo-spring-boot-3-webmvc` or `cd demo-spring-boot-3-webflux`

Then run:

```sh
mvn -Pnative clean spring-boot:build-image
```

**Comment by goafabric** [comment]
did so ... tree/2.x, folder webmvc .. produces the same exception
java -version gives

openjdk version "17.0.2" 2022-01-18 LTS
OpenJDK Runtime Environment Zulu17.32+13-CA (build 17.0.2+8-LTS)
OpenJDK 64-Bit Server VM Zulu17.32+13-CA (build 17.0.2+8-LTS, mixed mode, sharing)
andreas@MacBook-Air-von-Andreas demo-spring-boot-3-webmvc % mvn version


<img width="2560" alt="Bildschirm­foto 2023-03-10 um 10 12 44" src="https://user-images.githubusercontent.com/5617159/224274783-3d6bea4e-0f78-46a2-a21e-a101569d9640.png">

**Comment by bnasslahsen** [comment]
@goafabric, 

I am not testing with same version of openjdk/graalVM.

Try using:
$ java -version
openjdk version "17.0.5" 2022-10-18 LTS
OpenJDK Runtime Environment GraalVM 22.3.0 (build 17.0.5+8-LTS)
OpenJDK 64-Bit Server VM GraalVM 22.3.0 (build 17.0.5+8-LTS, mixed mode)

**Comment by goafabric** [comment]
i honestly dont think that this related to the java or graalvm version , as the error is reported by the spring aot processor
i will close the issue for now
as adding spring validation works for me .. and i've already wasted to much of my time with the 
(version) instability of spring aot 

thx 4 your support nontheless

**Comment by goafabric** [comment]
@bnasslahsen 
jus for the sake of information, the problem is gone with boot 3.0.5 .. i guess the fixed / changed the aot processor again
