### ISSUE TITLE
Regression of issue #2008 in version 2.0.3

### ISSUE THREAD

**Issue by matus-gazo** [springdoc/springdoc-openapi#2120]
**Describe the bug**

Hello,
After upgrading to version 2.0.3 I get the same (or at least similar) exception as in issue #2008 

**To Reproduce**
Steps to reproduce the behavior: Upgrade from springdoc 2.0.2 to 2.0.3
Rollback to 2.0.2 fixes the exception.

- What version of spring-boot you are using? 
3.0.4

- What modules and versions of springdoc-openapi are you using? 
api "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.3"

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.core.configuration.SpringDocKotlinConfiguration]: Constructor threw exception
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:321)
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/kotlin/KotlinModule$Builder
	at org.springdoc.core.configuration.SpringDocKotlinConfiguration.<init>(SpringDocKotlinConfiguration.kt:47)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210)
	... 21 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule$Builder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 28 common frames omitted

```

**Comment by bnasslahsen** [comment]
@matus-gazo ,

Please do not create duplicates

See #2114

**Comment by matus-gazo** [comment]
@bnasslahsen Sorry, missed that one, thanks!

**Comment by CynanX** [comment]
I am getting similar.

I do not use Kotlin in my project, however it is brought in by a test scoped dependency for:

```
            <groupId>au.com.dius.pact.provider</groupId>
            <artifactId>junit5</artifactId>
            <version>4.5.2</version>
            <scope>test</scope>
```

Should springdoc not only look at runtime dependencies to determine what support to provide?

**Comment by bnasslahsen** [comment]
@CynanX,

If you are using kotlin in your tests, then you should add the Jackson kotlin dependency as described in the documentation.

If you are not using kotlin in your tests, then you should exclude it from your test dependencies...

**Comment by CynanX** [comment]
I am not using Kotlin in my tests. The only use of Kotlin is the pact third part dependency that pulls a kotlin library in for its own use. I will attempt to exclude it. Thanks.

**Comment by bnasslahsen** [comment]
Exactly, that 's the idea!

**Comment by bnasslahsen** [comment]
duplicate deletion
