### ISSUE TITLE
Upgrade to 2.0.3 is breaking when com.fasterxml.jackson.module.kotlin.KotlinModule is not present in classpath

### ISSUE THREAD

**Issue by m-tilab** [springdoc/springdoc-openapi#2127]
**Describe the bug**

 when it is trying to upgrade to 2.0.3 build is failing as jackson kotlin module is not present in the classpath.

Below is the error.

`java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule$Builder`

**To Reproduce**

- What version of spring-boot you are using? **Spring Boot 3.0.4**
- What modules and versions of springdoc-openapi are you using? **org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.3**
- What is the actual and the expected result using OpenAPI Description (yml or json)?

**Expected behavior**

 start using a normal spring run and it should be up.

**Stack Trace**
`
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule$Builder
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at org.springdoc.core.configuration.SpringDocKotlinConfiguration.<init>(SpringDocKotlinConfiguration.kt:47) ~[springdoc-openapi-starter-common-2.0.3.jar:2.0.3]
`

**Comment by merlin-zaraza** [comment]
Same for me. Kotlin support should be optional. In 2.0.3 it's enabled by default. That's breaks pure Java configs. Why I have to add `springdoc.enable-kotlin=false` now? 

Also see #2114

**Comment by bnasslahsen** [comment]
@m-tilab,

Please do not create duplicates

See https://github.com/springdoc/springdoc-openapi/issues/2114

**Comment by bnasslahsen** [comment]
duplicate deletion
