### ISSUE TITLE
Upgrading to springdoc-openapi-starter-webmvc-ui:2.0.3 fails application startup

### ISSUE THREAD

**Issue by isatishp** [springdoc/springdoc-openapi#2144]
Upgrading from springdoc-openapi-starter-webmvc-ui:2.0.2 to 2.0.3 causes application startup to fail

Please find the stack trace below:

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springdoc.core.configuration.SpringDocKotlinConfiguration': Failed to instantiate
 [org.springdoc.core.configuration.SpringDocKotlinConfiguration]: Constructor threw exception
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:324) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:312) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1344) ~[spring-beans-6.0.6.jar:6.0.6
]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1188) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:561) ~[spring-beans-6.0.6.jar:6.0.6]       
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:961) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917) ~[spring-context-6.0.6.jar:6.0.6]        
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:584) ~[spring-context-6.0.6.jar:6.0.6]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.4.jar:3.0.4]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-3.0.4.jar:3.0.4]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-3.0.4.jar:3.0.4]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:310) ~[spring-boot-3.0.4.jar:3.0.4]
        at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.4.jar:3.0.4]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:59) ~[spring-core-6.0.6.jar:6.0.6]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:47) ~[spring-core-6.0.6.jar:6.0.6]
        at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1388) ~[spring-boot-3.0.4.jar:3.0.4]
        at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545) ~[spring-boot-test-3.0.4.jar:3.0.4]
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137) ~[spring-boot-test-3.0.4.jar:3.0.4]
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108) ~[spring-boot-test-3.0.4.jar:3.0.4]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:184) ~[spring-test-6.0.6.jar:6.
0.6]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:118) ~[spring-test-6.0.6.jar:6.0.6]    
        ... 67 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.core.configuration.SpringDocKotlinConfiguration]: Constructor threw exception     
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:223) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:110) ~[spring-beans-6.0.6.jar:6.0.6]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:321) ~[spring-beans-6.0.6.jar:6.0.6]
        ... 92 common frames omitted
Caused by: java.lang.NoClassDefFoundError: com/fasterxml/jackson/module/kotlin/KotlinModule$Builder
        at org.springdoc.core.configuration.SpringDocKotlinConfiguration.<init>(SpringDocKotlinConfiguration.kt:47) ~[springdoc-openapi-starter-common-2.0.3.jar:2.0.3]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:210) ~[spring-beans-6.0.6.jar:6.0.6]
        ... 94 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule$Builder
        ... 101 common frames omitted

- What version of spring-boot you are using: 3.0.4

This issue can be resolved by adding :
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        
  Expectation: The dependency should be transitively added.

**Comment by bnasslahsen** [comment]
see latest version before logging issues: 

- https://springdoc.org/v2/

**Comment by lbenedetto** [comment]
@bnasslahsen I think the confusion comes from the fact that, at least in my case, the project does not use any Kotlin. So even having read the docs you linked to, I would not expect to have to follow the steps in that section.

I think SpringDoc might be detecting some kotlin from a transitive dependency and then unnecessarily enabling Kotlin support.

**Comment by bnasslahsen** [comment]
> @bnasslahsen I think the confusion comes from the fact that, at least in my case, the project does not use any Kotlin. So even having read the docs you linked to, I would not expect to have to follow the steps in that section.
> 
> I think SpringDoc might be detecting some kotlin from a transitive dependency and then unnecessarily enabling Kotlin support.

@lbenedetto,

Not sure you read well the docs! Otherwise, you wouldn't assume wrong things.
Please also, do not create duplicate. This looks to be a duplicate of 2114.

-  First: Please before logging an issue. Try using the last stable version. 
-  And Read [CHANGELOG](https://github.com/springdoc/springdoc-openapi/blob/2.x/CHANGELOG.md) for more details.
- You have also a [guidance, when to use GITHUB Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).

Thus with last version, you should not have the same error as v2..0.3
`springdoc-openapi` is already detecting kotlin presence from your transitive dependencies...
The extra dependency `jackson-module-kotlin` asked in the documentation, is **only in case** you need to enable full `springdoc-openapi` kotlin support.

I hope you understand the message.

**Comment by lbenedetto** [comment]
I didn't create a duplicate issue, I commented on this existing issue. The issue you linked is the issue I commented on.

>Thus with last version, you should not have the same error as v2..0.3 
I'm running 2.0.4 with `springdoc-openapi-starter-webmvc-ui` and `springdoc-openapi-starter-common` (docs say I should because of spring security)

Docs say:
> For a project that uses Kotlin, you should use springdoc-openapi-starter-common. This dependency improves the support of Kotlin types.
> Your project should add jackson-module-kotlin to the list of dependencies
>The extra dependency jackson-module-kotlin asked in the documentation, is only in case you need to enable full springdoc-openapi kotlin support.

My project does not use Kotlin or need any amount of Kotlin support, so I assume that I don't have to worry about that stuff. 
However, it is detecting Kotlin via a chain of transitive dependencies facebook-java-business-sdk -> okhttp -> okio -> kotlin-stdlib.
So I need to set the `springdoc.enable-kotlin=false` flag.

I get it if you can't detect if any of my endpoints are actually using Kotlin and are instead just checking if Kotlin exists on the classpath, but I think the docs should just be a little more clear about what it means when it says "project that uses Kotlin". My casual reading of that makes me think of actually using Kotlin (ie, in our response models), and not just some nested transitive dependency using it for something that SpringDoc shouldn't have to interact with.

**Comment by bnasslahsen** [comment]
@lbenedetto,

You really do not read. it's duplicate of f https://github.com/springdoc/springdoc-openapi/issues/2114...
You are shipping kotlin dependencies ...

Note the project should not fail.  And you should not set the `springdoc.enable-kotlin=false`
Your analysis is wrong.

But if you believe, you found your solution. so be it then,

Just please, do not ask questions as you seem to know the right solution for you...

**Comment by lbenedetto** [comment]
Oops, #2114 is indeed a different ticket than #2144. I misread the ticket number and thought you were linking back to this ticket, so I didn't bother clicking on it.

And of course, you're also right that `springdoc.enable-kotlin=false` is only needed on 2.0.3, not 2.0.4
