### ISSUE TITLE
Spring Data MongoDB @Aggregation with single-value simple type fails with Springdoc

### ISSUE THREAD

**Issue by vgarmash** [springdoc/springdoc-openapi#2192]
Spring Data MongoDB supports various ways to define Aggregation on repository. You can see them all here: https://docs.spring.io/spring-data/mongodb/docs/current/reference/html/#mongodb.repositories.queries.aggregation. There is a possibility to define method on the repository which will return the type which is not a PersistentEntity but simple Java type:

```
public interface PersonRepository extends CrudRepository<Person, String> {

  @Aggregation("{ $group : { _id : null, total : { $sum : $age } } }")
  SumValue sumAgeUsingValueWrapper();                                              

  @Aggregation("{ $group : { _id : null, total : { $sum : $age } } }")
  Long sumAge();   

  @Aggregation("{ '$project': { '_id' : '$lastname' } }")
  List<String> findAllLastnames(); 

}
```

I tried to implement simple search on my repositories that will return `List<String>` instead of `List<MyPersistentEntity>` and I got this exception in the logs:

```
org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type class java.lang.String
	at org.springframework.data.mapping.context.MappingContext.getRequiredPersistentEntity(MappingContext.java:80)
	at org.springframework.data.mapping.context.PersistentEntities.getRequiredPersistentEntity(PersistentEntities.java:116)
	at org.springdoc.data.rest.utils.SpringDocDataRestUtils.lambda$customise$0(SpringDocDataRestUtils.java:122)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.springdoc.data.rest.utils.SpringDocDataRestUtils.customise(SpringDocDataRestUtils.java:118)
	at org.springdoc.data.rest.SpringRepositoryRestResourceProvider.customize(SpringRepositoryRestResourceProvider.java:314)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$getPaths$1(OpenApiResource.java:171)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springdoc.webmvc.api.OpenApiResource.lambda$getPaths$2(OpenApiResource.java:168)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:164)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:332)
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:268)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

What's interesting that adding `@RestResource(exported = false)` to the method or implicitly describing response doesn't help:
```
@Operation(responses = {
            @ApiResponse(responseCode = "200", content = {@Content(array = @ArraySchema(schema = @Schema(type = "string", implementation = String.class)))})
    })
```

**To Reproduce**

- What version of spring-boot you are using? - 2.7.10 or below
- What modules and versions of springdoc-openapi are you using? - 1.7.0
- Provide with a sample code (HelloController) or Test that reproduces the problem - Please take code samples form the Spring Data MongoDB documentation, provided above

**Expected behavior**
Spring Doc UI should be able to render schema properly with search methods returning single-valued simple types or arrays of them.

**Screenshots**
Spring Doc UI fails to return the schema:
![image](https://user-images.githubusercontent.com/1226001/229603652-c9bd279b-256c-4cc8-9767-601eabd0a638.png)

**Comment by bnasslahsen** [comment]
@vgarmash,

Spring Data MongoDB is not supported.

**Comment by vgarmash** [comment]
@bnasslahsen What do you mean? I am using Springdoc with Spring Data REST with MongoDB for last 2.5 years in production! Look at your site: https://springdoc.org/#spring-data-rest-support. Looking at Spring Data REST website https://spring.io/projects/spring-data-rest and there are multiple databases they support. 
![image](https://user-images.githubusercontent.com/1226001/229643057-ca0b061a-c2fb-402e-8865-83d5a8f1968a.png)


If your support for Spring Data is limited to certain implementation, please mention it in your documentation.
