### ISSUE TITLE
java.lang.ClassCastException: class jdk.proxy2.$Proxy222 cannot be cast to class javax.validation.constraints.Pattern

### ISSUE THREAD

**Issue by donahchoo** [springdoc/springdoc-openapi#2316]
**Describe the bug**

I'm using Spring Boot 2.7 still because Spring Boot 3 does not yet support Jetty 12.  Because of this I'm still using `org.springdoc:springdoc-openapi-ui::1.7.0`.

I have controllers that are using `jakarta.validation.constraints.Pattern` like so

```
    @PutMapping(value = "/update/{petId}")
    ResponseEntity<Void> updatePet(@Pattern(regexp = "[\\p{Alnum}-_]{22}") String petId,
                                         @RequestParam String petType)
``` 

When I try access the swagger endpoint at `http://localhost:8080/v3/api-docs.yaml` to download the docs I get the below exception.  I'm not sure why this is happening because line 652 in AbstractRequestService appears to be trying to cast a Pattern to a Pattern..

`Pattern pattern = (Pattern) annos.get(Pattern.class.getSimpleName());`

When I evaluate the `get` in IntelliJ I see:

```java
@jakarta.validation.constraints.Pattern(flags={}, groups={}, 
message="{jakarta.validation.constraints.Pattern.message}", 
payload={}, regexp="[\\p{Alnum}-_]{22}")
```

Exception:

```java
java.lang.ClassCastException: class jdk.proxy2.$Proxy222 cannot be cast to class javax.validation.constraints.Pattern
 (jdk.proxy2.$Proxy222 is in module jdk.proxy2 of loader 'app'; javax.validation.constraints.Pattern is in unnamed module of loader
 'app') 	at org.springdoc.core.AbstractRequestService.applyValidationsToSchema(AbstractRequestService.java:652) 	at 
org.springdoc.core.AbstractRequestService.applyBeanValidatorAnnotations(AbstractRequestService.java:519) 	at 
org.springdoc.core.AbstractRequestService.build(AbstractRequestService.java:278) 	at 
org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:448) 	at 
org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:595) 	at 
org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:250) 	at 
org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:200) 	at 
org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:323) 	at 
org.springdoc.webmvc.api.OpenApiResource.openapiYaml(OpenApiResource.java:178) 	at 
org.springdoc.webmvc.api.OpenApiWebMvcResource.openapiYaml(OpenApiWebMvcResource.java:142) 	at 
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at 
java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 	at 
java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at 
java.base/java.lang.reflect.Method.invoke(Method.java:568) 	at 
org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) 	at 
org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:965) 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) 	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:497) 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:584) 	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:764) 	at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1665)
```

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.7.0  is the latest Open Source release supporting Spring Boot 2.x and 1.x.

An extended support for [springdoc-openapi v1](https://springdoc.org/v1)
project is now available for organizations that need support beyond 2023.

For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)
