### ISSUE TITLE
ExceptionHandlingWebHandler by BlockingSingleSubscriber

### ISSUE THREAD

**Issue by earthspiligrim** [springdoc/springdoc-openapi#2338]
**I am getting block()/blockFirst()/blockLast() exception with spring webflux project**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- I am using the following libraries in my project.
- spring.boot.version - 2.6.6
            <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-core</artifactId>
            <version>1.6.6</version> 
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.6.6</version>
        </dependency>

Here is my RequestInterceptor implementation.
public class RequestInterceptor implements WebFilter{

	private static final List<String> SWAGGER_ENDPOINTS = Arrays.asList(
			"/swagger-doc/v3/api-docs",
			"/swagger-config",
			"/spring-docs",
			"/swagger-resources",
			"/swagger-ui",

			"/swagger-doc/webjars/swagger-ui/index.html",
			"/swagger-doc/v3/api-docs/swagger-config",
			"/swagger-doc/webjars/swagger-ui/swagger-initializer.js"
	);

	private final boolean encodeBytes = false;

	@Override
	public Mono<Void> filter(ServerWebExchange exchange, WebFilterChain chain) {
		if ((SWAGGER_ENDPOINTS.stream().anyMatch(exchange.getRequest().getPath().value()::contains))) {
			return chain.filter(exchange);
		} else {

Here is my main class implementation

      @SpringBootApplication
      @EnableCaching
      @EnableWebFlux
      @Slf4j
      @OpenAPIDefinition(info = @Info(
		      title = "my app title",
		      version = "1.1.1",
		      description = "my app description"
      ))
      public class SwaggerWebFluxImplementation {
           public static void main(String[] args) throws Exception {

		SpringApplication.run(MyApp.class, args);
	    }
        
          @Bean
	@RouterOperations({
			@RouterOperation(
					path = "/health",
					produces = {MediaType.APPLICATION_JSON_VALUE},
					method = RequestMethod.GET,
					operation = @Operation(
							tags = {"Health Check"},
							summary = "Health Check",
							operationId = "healthCheck",
							responses = {
									@ApiResponse(
											responseCode = "200",
											description = "Health Check OK",
											content = @Content(schema = @Schema(implementation = String.class))
									),
									@ApiResponse(
											responseCode = "400",
											description = "Invalid Request",
											content = @Content(schema = @Schema(implementation = String.class))
									),
									@ApiResponse(
											responseCode = "500",
											description = "Task failed",
											content = @Content(schema = @Schema(implementation = String.class))
									)
							}
					)
			)
	})
	RouterFunction<ServerResponse> healthCheck() {
		return RouterFunctions.route(RequestPredicates.GET("/health"),
				request -> ServerResponse.ok().body(Mono.just("SUCCESS"), String.class));
	}
      }

Note: the swagger works fine for the first 30 minutes but i am getting the below exception exactly after 30 minutes 

    Exception is of type CustomGlobalException
    java.lang.IllegalStateException: block()/blockFirst()/blockLast() are blocking, which is not supported in thread reactor-http-nio-9
	    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
	    Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
    Error has been observed at the following site(s):
	    |_ checkpoint ⇢ com.abc.def.nextgen.appname.RequestInterceptor [DefaultWebFilterChain]
	    |_ checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	    |_ checkpoint ⇢ HTTP GET "/swagger-doc/v3/api-docs" [ExceptionHandlingWebHandler]
    Stack trace:
		    at reactor.core.publisher.BlockingSingleSubscriber.blockingGet(BlockingSingleSubscriber.java:83)
		    at reactor.core.publisher.Flux.blockLast(Flux.java:2519)
		    at com.azure.core.util.paging.ContinuablePagedByIteratorBase.requestPage(ContinuablePagedByIteratorBase.java:102)
		    at java.base/java.lang.Iterable.forEach(Iterable.java:74)
		    at java.base/java.util.Optional.map(Optional.java:265)
    org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)
		    at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver$DefaultResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:123)
		    at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.findPropertyValue(ConfigurationPropertySourcesPropertyResolver.java:97)
		    at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:74)
		    at org.springframework.boot.context.properties.source.ConfigurationPropertySourcesPropertyResolver.getProperty(ConfigurationPropertySourcesPropertyResolver.java:60)
		    at org.springframework.core.env.AbstractEnvironment.getProperty(AbstractEnvironment.java:594)
		    at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:153)
		    at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$1.getProperty(PropertySourcesPlaceholderConfigurer.java:149)
		    at org.springframework.core.env.PropertySourcesPropertyResolver.getProperty(PropertySourcesPropertyResolver.java:85)
		    at org.springframework.core.env.PropertySourcesPropertyResolver.getPropertyAsRawString(PropertySourcesPropertyResolver.java:74)
		    at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:153)
		    at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
		    at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
		    at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
		    at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191)
		    at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:936)
		    at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.resolveEmbeddedValuesAndExpressions(AbstractNamedValueArgumentResolver.java:165)
		    at org.springframework.web.reactive.result.method.annotation.AbstractNamedValueArgumentResolver.lambda$getDefaultValue$1(AbstractNamedValueArgumentResolver.java:212)
		    at reactor.core.publisher.MonoSupplier.subscribe(MonoSupplier.java:56)
		    at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
		    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onComplete(FluxSwitchIfEmpty.java:81)
		    at reactor.core.publisher.Operators.complete(Operators.java:136)
		    at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:145)
		    at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53)
		    at reactor.core.publisher.Mono.subscribe(Mono.java:4135)
		    at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
		    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
		    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onComplete(MonoFlatMap.java:181)
		    at reactor.core.publisher.Operators.complete(Operators.java:136)
		    at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:120)
		    at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
		    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
		    at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		    at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:73)
		    at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
		    at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:281)
		    at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:860)
		    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:127)
		    at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
		    at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2397)
		    at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.request(MonoPeekTerminal.java:139)
		    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.request(FluxMapFuseable.java:169)
		    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2193)
		    at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onSubscribe(Operators.java:2067)
		    at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onSubscribe(FluxMapFuseable.java:96)
		    at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onSubscribe(MonoPeekTerminal.java:152)
		    at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
		    at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
		    at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:448)
		    at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:218)
		    at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:164)
		    at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:86)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		    at reactor.core.publisher.Mono.subscribe(Mono.java:4150)
		    at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
		    at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
		    at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
		    at reactor.core.publisher.MonoDeferContextual.subscribe(MonoDeferContextual.java:55)
		    at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:967)
		    at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:677)
		    at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478)
		    at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:570)
		    at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		    at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:222)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		    at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
		    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
		    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
		    at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
		    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
		    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
		    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
		    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
		    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
		    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
		    at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
		    at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		    at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		    at java.base/java.lang.Thread.run(Thread.java:834)

**To Reproduce**

- What version of spring-boot you are using?
- 2.6.6
- What modules and versions of springdoc-openapi are you using?
- springdoc-openapi-webflux-core-1.6.6 and springdoc-openapi-webflux-ui-1.6.6
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

I expect not to have any blocking with swagger docs

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.7.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.
An extended support for [springdoc-openapi v1](https://springdoc.org/v1) project is now available for organizations that need support beyond 2023.
For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

**Comment by earthspiligrim** [comment]
i used 1.7.0 and i still see the issue. can you please suggest a fix for this?
