### ISSUE TITLE
Integration tests fail with Spring Boot version 3.2.0-RC1

### ISSUE THREAD

**Issue by donalmurtagh** [springdoc/springdoc-openapi#2416]
**Describe the bug**

After upgrading a Spring Boot 3.1.5 app to 3.2.0-RC1, the integration tests throw an exception. The stacktrace indicates that the cause of the problem is springdoc. If I disable springdoc by setting this property, the tests pass.

```yml
springdoc:
  api-docs:
    enabled: false
```

**To Reproduce**

- [create a Spring Boot v3.2.0-RC1 app](https://start.spring.io)
- Add the (Gradle) dependency `implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'`
- Add an integration test, e.g.

```java
@SpringBootTest
public class IntegrationTest {
    @Test
    void testIt() {
        Assertions.assertTrue(true);
    }
}
```
 - run the tests under JDK21 (I didn't try other JDK versions) `./gradlew test`
 
**Expected behavior**

The test fails because of the following exception thrown by springdoc. If you disable springdoc, the test passes

```
Error creating bean with name 'org.springdoc.core.configuration.SpringDocKotlinConfiguration': Unexpected exception during bean creation
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springdoc.core.configuration.SpringDocKotlinConfiguration': Unexpected exception during bean creation
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:536)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325)
	at app//org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323)
	at app//org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at app//org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at app//org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:947)
	at app//org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616)
	at app//org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at app//org.springframework.boot.SpringApplication.refresh(SpringApplication.java:748)
	at app//org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:450)
	at app//org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137)
	at app//org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58)
	at app//org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46)
	at app//org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1436)
	at app//org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:544)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137)
	at app//org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:225)
	at app//org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:152)
	at app//org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:130)
	at app//org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:141)
	at app//org.springframework.test.context.support.DependencyInjectionTestExecutionListener.prepareTestInstance(DependencyInjectionTestExecutionListener.java:97)
	at app//org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:247)
	at app//org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:163)
	at java.base@21/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@21/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base@21/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
	at java.base@21/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@21/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@21/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base@21/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base@21/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base@21/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base@21/java.util.Optional.orElseGet(Optional.java:364)
	at java.base@21/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base@21/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: java.lang.NoSuchMethodError: 'boolean kotlin.reflect.KClass.isValue()'
	at org.springframework.beans.BeanUtils$KotlinDelegate.findPrimaryConstructor(BeanUtils.java:850)
	at org.springframework.beans.BeanUtils.findPrimaryConstructor(BeanUtils.java:282)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1190)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:563)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523)
	... 37 more
```

**Comment by donalmurtagh** [comment]
The cause of this problem was a conflict between the Kotlin version required by SpringDoc and another dependency (junit-insights). I removed the other dependency, and the problem was resolved.

**Comment by bhagyashree-marekar-polestar** [comment]
I upgraded the Spring Boot version from 3.1.6 to 3.2.1, which is the latest, and java version is 17, and the integration tests are failing with the following error:

**java.lang.NoSuchMethodError: 'java.util.List org.springframework.test.context.MergedContextConfiguration.getPropertySourceDescriptors()'**

**Comment by gsant07** [comment]
I upgrade from Springboot 2.7 to 3.2.4 version , java 17 and they are failing with this issue 401 UNAUTHORIZED in Integration Tests. They were working fine with before version of java 11 and springboot 2.7
