### ISSUE TITLE
java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException

### ISSUE THREAD

**Issue by lin1005q** [springdoc/springdoc-openapi#2423]
**Describe the bug**

1. start boot applicaiton
2. open http://127.0.0.1:8080/v3/api-docs
3. 500 error

java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException

**To Reproduce**

- What version of spring-boot you are using? 
3.1.1
- What modules and versions of springdoc-openapi are you using?

```xml
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>2.2.0</version>
        </dependency>
```

- What is the actual and the expected result using OpenAPI Description (yml or json)?
json
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

```text
2023-11-08T17:56:33.983+08:00 ERROR 59354 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed: java.lang.NoClassDefFoundError: javax/activation/MimeTypeParseException] with root cause

java.lang.ClassNotFoundException: javax.activation.MimeTypeParseException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[na:na]
	at java.base/java.lang.Class.getDeclaredFields0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297) ~[na:na]
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371) ~[na:na]
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector._findFields(AnnotatedFieldCollector.java:73) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collect(AnnotatedFieldCollector.java:48) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collectFields(AnnotatedFieldCollector.java:43) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._fields(AnnotatedClass.java:370) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:342) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:519) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:445) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:286) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueMethod(POJOPropertiesCollector.java:412) ~[jackson-databind-2.15.2.jar:2.15.2]
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueMethod(BasicBeanDescription.java:252) ~[jackson-databind-2.15.2.jar:2.15.2]
	at io.swagger.v3.core.jackson.ModelResolver.findJsonValueType(ModelResolver.java:1055) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:401) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:155) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:69) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.ResponseSupportConverter.resolve(ResponseSupportConverter.java:79) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.SchemaPropertyDeprecatingConverter.resolve(SchemaPropertyDeprecatingConverter.java:92) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.PolymorphicModelConverter.resolve(PolymorphicModelConverter.java:77) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:97) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:445) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:155) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:69) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.ResponseSupportConverter.resolve(ResponseSupportConverter.java:79) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.SchemaPropertyDeprecatingConverter.resolve(SchemaPropertyDeprecatingConverter.java:92) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.PolymorphicModelConverter.resolve(PolymorphicModelConverter.java:77) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:97) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:706) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:155) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:69) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.ResponseSupportConverter.resolve(ResponseSupportConverter.java:79) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.SchemaPropertyDeprecatingConverter.resolve(SchemaPropertyDeprecatingConverter.java:92) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.converters.PolymorphicModelConverter.resolve(PolymorphicModelConverter.java:77) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:97) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at io.swagger.v3.core.converter.ModelConverters.resolveAsResolvedSchema(ModelConverters.java:153) ~[swagger-core-jakarta-2.2.15.jar:2.2.15]
	at org.springdoc.core.utils.SpringDocAnnotationsUtils.extractSchema(SpringDocAnnotationsUtils.java:122) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.service.GenericParameterService.calculateSchema(GenericParameterService.java:374) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.service.AbstractRequestService.buildParam(AbstractRequestService.java:555) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.service.AbstractRequestService.buildParams(AbstractRequestService.java:520) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.core.service.AbstractRequestService.build(AbstractRequestService.java:326) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:493) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:673) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.webmvc.api.OpenApiResource.lambda$calculatePath$11(OpenApiResource.java:219) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:200) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at org.springdoc.webmvc.api.OpenApiResource.lambda$getPaths$2(OpenApiResource.java:170) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:149) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:350) ~[springdoc-openapi-starter-common-2.2.0.jar:2.2.0]
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:124) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at org.springdoc.webmvc.api.OpenApiWebMvcResource.openapiJson(OpenApiWebMvcResource.java:111) ~[springdoc-openapi-starter-webmvc-api-2.2.0.jar:2.2.0]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:207) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:152) ~[spring-web-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:118) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:884) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1081) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:974) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1011) ~[spring-webmvc-6.0.10.jar:6.0.10]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.0.10.jar:6.0.10]

```

**Additional context**

**Comment by bnasslahsen** [comment]
Not reproducible.
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
