### ISSUE TITLE
Adding dependency to springdoc causes JSP not working on spring-boot 3.2.0 and jetty embedded server 12

### ISSUE THREAD

**Issue by krzaq464** [springdoc/springdoc-openapi#2455]
Spring-boot web application with minimum setup to support JSPs is throwing an error when org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0 is added. 
Here's the result of calling any JSP:

<html>
<body>
<h2 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">HTTP ERROR 404 JSP file [/pages/error/500.jsp] not found</h2>
URI: | http://localhost:8080/testowy
-- | --
404
JSP file [/pages/error/500.jsp] not found
org.apache.jasper.JasperException: java.io.FileNotFoundException: JAR entry META-INF/resources/WEB-INF/tagPlugins.xml not found in C:\Users\Dom\IdeaProjects\minimumjsp\target\minimumjsp-0.0.1-SNAPSHOT.war!/WEB-INF/lib/swagger-ui-5.10.3.jar
java.io.FileNotFoundException: JAR entry META-INF/resources/WEB-INF/tagPlugins.xml not found in C:\Users\Dom\IdeaProjects\minimumjsp\target\minimumjsp-0.0.1-SNAPSHOT.war!/WEB-INF/lib/swagger-ui-5.10.3.jar

<h3 style="color: rgb(0, 0, 0); font-family: &quot;Times New Roman&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Caused by:</h3><pre style="color: rgb(0, 0, 0); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">org.apache.jasper.JasperException: java.io.FileNotFoundException: JAR entry META-INF/resources/WEB-INF/tagPlugins.xml not found in C:\Users\Dom\IdeaProjects\minimumjsp\target\minimumjsp-0.0.1-SNAPSHOT.war!/WEB-INF/lib/swagger-ui-5.10.3.jar
	at org.apache.jasper.compiler.TagPluginManager.init(TagPluginManager.java:109)
	at org.apache.jasper.compiler.TagPluginManager.apply(TagPluginManager.java:58)
	at org.apache.jasper.compiler.Compiler.generateJava(Compiler.java:252)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:396)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:372)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:356)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:603)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:396)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:380)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:328)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:110)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet.Dispatcher.forward(Dispatcher.java:124)
	at org.springframework.web.servlet.view.InternalResourceView.renderMergedOutputModel(InternalResourceView.java:171)
	at org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:314)
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1431)
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1167)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885)
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)
	at org.eclipse.jetty.ee10.servlet.ServletHolder.handle(ServletHolder.java:736)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1609)
	at org.eclipse.jetty.ee10.websocket.servlet.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:195)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)
	at org.eclipse.jetty.ee10.servlet.FilterHolder.doFilter(FilterHolder.java:205)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1581)
	at org.eclipse.jetty.ee10.servlet.ServletHandler$MappedServlet.handle(ServletHandler.java:1542)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.dispatch(ServletChannel.java:886)
	at org.eclipse.jetty.ee10.servlet.ServletChannel.handle(ServletChannel.java:491)
	at org.eclipse.jetty.ee10.servlet.ServletHandler.handle(ServletHandler.java:463)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:571)
	at org.eclipse.jetty.ee10.servlet.SessionHandler.handle(SessionHandler.java:693)
	at org.eclipse.jetty.server.handler.ContextHandler.handle(ContextHandler.java:809)
	at org.eclipse.jetty.server.Server.handle(Server.java:179)
	at org.eclipse.jetty.server.internal.HttpChannelState$HandlerInvoker.run(HttpChannelState.java:649)
	at org.eclipse.jetty.server.internal.HttpConnection.onFillable(HttpConnection.java:471)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:322)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100)
	at org.eclipse.jetty.io.SelectableChannelEndPoint$1.run(SelectableChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:971)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.doRunJob(QueuedThreadPool.java:1196)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1151)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.FileNotFoundException: JAR entry META-INF/resources/WEB-INF/tagPlugins.xml not found in C:\Users\Dom\IdeaProjects\minimumjsp\target\minimumjsp-0.0.1-SNAPSHOT.war!/WEB-INF/lib/swagger-ui-5.10.3.jar
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.lambda$notFoundConnection$1(JarUrlConnection.java:365)
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.throwFileNotFound(JarUrlConnection.java:329)
	at org.springframework.boot.loader.net.protocol.jar.JarUrlConnection.getInputStream(JarUrlConnection.java:181)
	at java.base/java.net.URL.openStream(URL.java:1161)
	at org.apache.tomcat.util.descriptor.tagplugin.TagPluginParser.parse(TagPluginParser.java:52)
	at org.apache.jasper.compiler.TagPluginManager.init(TagPluginManager.java:106)
	... 68 more</pre>
</body>
</html>

Spring boot version 3.2.0
Jetty embedded server version: 12.0.3
Spring-doc version: 2.3.0
Java version: openjdk-17
Maven version: 3.6.3

**To Reproduce**
- Build the app with clean install.
- Run the app as .war: 
`java -jar minimumjsp-0.0.1-SNAPSHOT.war`
- navigate to 'http://localhost:8080/testowy'

Please note that beside adding 'springdoc-openapi-starter-webmvc-ui', there was no spring-doc configuration added.
Here's the simple project:
[minimumjsp.zip](https://github.com/springdoc/springdoc-openapi/files/13647745/minimumjsp.zip)

**Comment by krzaq464** [comment]
From what I already figured out is that it may be caused by transitive webjars dependencies

**Comment by bnasslahsen** [comment]
@krzaq464,

The application runs fine from the IDE
<img width="1618" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/13404829/fcc434f9-5639-48bf-930b-86b1c73eae27">

check your packaging setup
