### ISSUE TITLE
Exception: re spring.mvc.servlet.path at Spring Boot server startup

### ISSUE THREAD

**Issue by dcanfield40** [springdoc/springdoc-openapi#2457]
I am following the "No additional configuration is needed" instructions for Springdoc, and I'm attempting to add the dependency to an existing Spring Boot 3.09 project with: 

      <dependency>
          <groupId>org.springdoc</groupId>
          <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
          <version>2.3.0</version>
      </dependency>

When I start Spring, I see an error with the root cause being:  

`Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'spring.mvc.servlet.path:#{null}' in value "${spring.mvc.servlet.path:#{null}}"
        at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:180)
        at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:126)
        at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:239)
        at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:210)
        at org.springframework.context.support.PropertySourcesPlaceholderConfigurer.lambda$processProperties$0(PropertySourcesPlaceholderConfigurer.java:191)
        at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:920)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1358)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:713)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:696)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:145)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:483)
`

It doesn't seem to matter if I have the _spring.mvc.servlet.path_ property explicitly set or not.  For this project, the default (i.e. "/") is what we need. Thanks.

**Comment by bnasslahsen** [comment]
@dcanfield40,

Not reproducible.
You have demos how to setup projects here: https://github.com/springdoc/springdoc-openapi-demos/tree/2.x/demo-spring-boot-3-webmvc

**Comment by ragro** [comment]
facing same issue.
