### ISSUE TITLE
JavaDoc integration not working with SnakeCaseStrategy property naming

### ISSUE THREAD

**Issue by joarobles** [springdoc/springdoc-openapi#2484]
**Describe the bug**

When trying to generate Schema description from JavaDoc comments, it's not working as expected for fields that not match exactly with their JSON representation (camelCase to snake_case for example).

**To Reproduce**

- What version of spring-boot you are using?
`spring-boot: 3.2.1`

- What modules and versions of springdoc-openapi are you using?
`springdoc-openapi-starter-webmvc-ui: 2.3.0`
`therapi-runtime-javadoc: 0.15.0`

- What is the actual and the expected result using OpenAPI Description (yml or json)?

Actual:

```json
{
    "SearchRequest": {
        "required": [
            "org_id",
            "organization_id"
        ],
        "type": "object",
        "properties": {
            "organization_id": {
                "type": "integer",
                "format": "int64"
            },
            "org_id": {
                "type": "integer",
                "description": "All search requests must specify an Organization to filter the results by (exact match). I.e.: <code>1234</code>",
                "format": "int64"
            }
        }
    }
}
```

Expected:

```json
{
    "SearchRequest": {
        "required": [
            "org_id",
            "organization_id"
        ],
        "type": "object",
        "properties": {
            "organization_id": {
                "type": "integer",
                "description": "All search requests must specify an Organization to filter the results by (exact match). I.e.: <code>1234</code>",
                "format": "int64"
            },
            "org_id": {
                "type": "integer",
                "description": "All search requests must specify an Organization to filter the results by (exact match). I.e.: <code>1234</code>",
                "format": "int64"
            }
        }
    }
}
```

- Provide with a sample code (HelloController) or Test that reproduces the problem

```java
@Data
@Builder
@AllArgsConstructor
@EqualsAndHashCode(callSuper = false)
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class SearchRequest {

  /**
   * All search requests must specify an Organization to filter the results by (exact match)
   * I.e.: <code>1234</code>
   */
  private @NotNull final Long organizationId;

  @Schema(description = "All search requests must specify an Organization to filter the results by (exact match). I.e.: <code>1234</code>")
  private @NotNull final Long orgId;

}
```

**Expected behavior**

- A clear and concise description of what you expected to happen.
I'd expect all fields to have the same schema description in the generated json.

- What is the expected result using OpenAPI Description (yml or json)?
I'd expect all fields to have the same schema description in the generated json.

**Screenshots**
N/A

**Additional context**

**Comment by Heromyth** [comment]
It works well. I'm using these dependencies
```xml
		<!-- Springdoc -->
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc.version}</version>
		</dependency>

		<dependency>
			<groupId>com.github.therapi</groupId>
			<artifactId>therapi-runtime-javadoc-scribe</artifactId>
			<version>0.15.0</version>
			<scope>provided</scope>
		</dependency>

		<dependency>
			<groupId>com.github.therapi</groupId>
			<artifactId>therapi-runtime-javadoc</artifactId>
			<version>0.15.0</version>
		</dependency>
```

The output is here
![图片](https://github.com/springdoc/springdoc-openapi/assets/1275109/33679cc5-5660-4bb1-b299-18656cbe20f8)

**Comment by Heromyth** [comment]
However, there is a NullPointerException:

```
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Method.getDeclaringClass()" because "method" is null
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.getJavadoc(RuntimeJavadoc.java:165)
	at com.github.therapi.runtimejavadoc.RuntimeJavadoc.getJavadoc(RuntimeJavadoc.java:161)
	at org.springdoc.core.providers.SpringDocJavadocProvider.getMethodJavadocDescription(SpringDocJavadocProvider.java:90)
	at org.springdoc.core.customizers.JavadocPropertyCustomizer.lambda$setJavadocDescription$6(JavadocPropertyCustomizer.java:169)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at org.springdoc.core.customizers.JavadocPropertyCustomizer.lambda$setJavadocDescription$7(JavadocPropertyCustomizer.java:168)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at org.springdoc.core.customizers.JavadocPropertyCustomizer.setJavadocDescription(JavadocPropertyCustomizer.java:159)
	at org.springdoc.core.customizers.JavadocPropertyCustomizer.resolve(JavadocPropertyCustomizer.java:109)
	at org.springdoc.core.converters.PageableOpenAPIConverter.resolve(PageableOpenAPIConverter.java:93)
	at org.springdoc.core.converters.SortOpenAPIConverter.resolve(SortOpenAPIConverter.java:83)
	at io.swagger.v3.core.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:97)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:477)
	at org.springdoc.core.converters.WebFluxSupportConverter.resolve(WebFluxSupportConverter.java:86)
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:155)
	at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:69)
```

**Comment by joarobles** [comment]
> It works well. I'm using these dependencies
> 
> ```
> 		
> 		<dependency>
> 			<groupId>org.springdoc</groupId>
> 			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
> 			<version>${springdoc.version}</version>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>com.github.therapi</groupId>
> 			<artifactId>therapi-runtime-javadoc-scribe</artifactId>
> 			<version>0.15.0</version>
> 			<scope>provided</scope>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>com.github.therapi</groupId>
> 			<artifactId>therapi-runtime-javadoc</artifactId>
> 			<version>0.15.0</version>
> 		</dependency>
> ```
> 
> The output is here ![图片](https://private-user-images.githubusercontent.com/1275109/297950061-33679cc5-5660-4bb1-b299-18656cbe20f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU5MjQ5NDAsIm5iZiI6MTcwNTkyNDY0MCwicGF0aCI6Ii8xMjc1MTA5LzI5Nzk1MDA2MS0zMzY3OWNjNS01NjYwLTRiYjEtYjI5OS0xODY1NmNiZTIwZjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjJUMTE1NzIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGE2NGZhZjc0YWY3MmQ1N2I1N2FlNjFmNDIzODlmNmI0M2I1Zjc2MmM1MDkwOTc5YjBmNWIzOTUxOGI3ZmMxOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hiBD7pMwII3zsA02pKxi00Eh25vtPAiYDNXQvu5auiU)

But as far as I can see you are not using `SnakeCaseStrategy`, your attributes are all in camel case.
