### ISSUE TITLE
Issue when using springboot 3, kotlin and OPENAPI_3_1

### ISSUE THREAD

**Issue by dionisioC** [springdoc/springdoc-openapi#2522]
**Describe the bug**

When using OPENAPI_3_1 the openapi json file generated is not correct, it says unresolved reference. this is not happenig if the setting is not in place.

Not sure if it is a bug or I am missing something. Maybe is an issue of the maven plugin

**To Reproduce**

- What version of spring-boot you are using?
      - 3.2.3
- What modules and versions of springdoc-openapi are you using?
  -         <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>2.3.0</version>
        </dependency>
- What is the actual and the expected result using OpenAPI Description (yml or json)?
    - A josn that is malformed, the expected is a correct json

This is the wrong json
```json
{
   "openapi":"3.1.0",
   "info":{
      "title":"OpenAPI definition",
      "version":"v0"
   },
   "servers":[
      {
         "url":"http://localhost:8080",
         "description":"Generated server url"
      }
   ],
   "paths":{
      "/test":{
         "get":{
            "tags":[
               "hello-controller"
            ],
            "summary":"Test",
            "description":"This is a test",
            "operationId":"getTest",
            "responses":{
               "200":{
                  "description":"ok",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/A"
                        }
                     }
                  }
               },
               "404":{
                  "description":"Error",
                  "content":{
                     "application/json":{
                        "schema":{
                           
                        }
                     }
                  }
               }
            }
         }
      }
   },
   "components":{
      "schemas":{
         "A":{
            "properties":{
               "b":{
                  "type":"array",
                  "items":{
                     "$ref":"#/components/schemas/B"
                  }
               }
            },
            "required":[
               "b"
            ]
         }
      }
   }
}
```

Using https://apitools.dev/swagger-parser/online/ provides the following error

```test
Token "B" does not exist.

Error: Token "B" does not exist.
    at o (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:95564)
    at https://apitools.dev/swagger-parser/online/js/bundle.min.js:29:45042

Token "B" does not exist.
    at Pointer.resolve (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:26126)
    at $Ref.resolve (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:28046)
    at $Refs._resolve (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:30513)
    at dereference$Ref (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14559)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14259)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
    at dereference$Ref (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14744)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14259)
    at crawl (https://apitools.dev/swagger-parser/online/js/bundle.min.js:1:14354)
```
Using https://editor.swagger.io/

Gives
```test
Errors
Hide
 
Structural error at openapi
should match pattern "^3\.0\.\d(-.+)?$"
pattern: ^3\.0\.\d(-.+)?$
Jump to line 1
Semantic error at components.schemas.A.properties.b.items.$ref
$refs must reference a valid location in the document
```

This is the rigth json (no OPENAPI_3_1 setting)

```json
{
   "openapi":"3.0.1",
   "info":{
      "title":"OpenAPI definition",
      "version":"v0"
   },
   "servers":[
      {
         "url":"http://localhost:8080",
         "description":"Generated server url"
      }
   ],
   "paths":{
      "/test":{
         "get":{
            "tags":[
               "hello-controller"
            ],
            "summary":"Test",
            "description":"This is a test",
            "operationId":"getTest",
            "responses":{
               "200":{
                  "description":"ok",
                  "content":{
                     "application/json":{
                        "schema":{
                           "$ref":"#/components/schemas/A"
                        }
                     }
                  }
               },
               "404":{
                  "description":"Error",
                  "content":{
                     "application/json":{
                        "schema":{
                           "type":"string"
                        }
                     }
                  }
               }
            }
         }
      }
   },
   "components":{
      "schemas":{
         "A":{
            "required":[
               "b"
            ],
            "type":"object",
            "properties":{
               "b":{
                  "type":"array",
                  "items":{
                     "$ref":"#/components/schemas/B"
                  }
               }
            }
         },
         "B":{
            "required":[
               "c",
               "d"
            ],
            "type":"object",
            "properties":{
               "c":{
                  "type":"string"
               },
               "d":{
                  "type":"string"
               }
            }
         }
      }
   }
}
```

- Provide with a sample code (HelloController) or Test that reproduces the problem
In this repo there is an example, with maven clean install generates a proper json. If you uncomment the setting OPENAPI_3_1 it generates a non compliant json
https://github.com/dionisioC/openapi-test/tree/master

**Expected behavior**

The file is generated without issues

**Comment by dionisioC** [comment]
Sorry, looking for more info I saw it duplicates other closed issues like https://github.com/springdoc/springdoc-openapi/issues/2448

**Comment by dionisioC** [comment]
Sorry looking for more info seems it is a duplicate of other issues like https://github.com/springdoc/springdoc-openapi/issues/2448
