### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.swagger.v3.oas.annotations.StringToClassMapItem[] io.swagger.v3.oas.annotations.media.Schema.dependentSchemas()'

### ISSUE THREAD

**Issue by KaseiHaku** [springdoc/springdoc-openapi#2586]
**Describe the bug**

org.springdoc:springdoc-openapi-starter-webflux-ui:2.5.0
When I access /swagger-ui.html , the following error is reported in the backend

java.lang.NoSuchMethodError: 'io.swagger.v3.oas.annotations.StringToClassMapItem[] io.swagger.v3.oas.annotations.media.Schema.dependentSchemas()'
2024-05-01T17:35:38.916204960Z 	at io.swagger.v3.core.util.AnnotationsUtils.hasSchemaAnnotation(AnnotationsUtils.java:108) ~[swagger-core-jakarta-2.2.21.jar!/:2.2.21]
2024-05-01T17:35:38.916207774Z 	at org.springdoc.core.utils.SpringDocAnnotationsUtils.getMediaType(SpringDocAnnotationsUtils.java:392) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916210247Z 	at org.springdoc.core.utils.SpringDocAnnotationsUtils.getContent(SpringDocAnnotationsUtils.java:185) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916212719Z 	at org.springdoc.core.service.RequestBodyService.buildResquestBodyContent(RequestBodyService.java:147) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916215165Z 	at org.springdoc.core.service.RequestBodyService.buildRequestBodyFromDoc(RequestBodyService.java:128) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916218349Z 	at org.springdoc.core.service.RequestBodyService.buildRequestBodyFromDoc(RequestBodyService.java:235) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916220893Z 	at org.springdoc.core.service.OperationService.parse(OperationService.java:158) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916223722Z 	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:481) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916226669Z 	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:676) ~[springdoc-openapi-starter-common-2.5.0.jar!/:2.5.0]
2024-05-01T17:35:38.916229124Z 	at org.springdoc.webflux.api.OpenApiResource.lambda$calculatePath$5(OpenApiResource.java:191) ~[springdoc-openapi-starter-webflux-api-2.5.0.jar!/:2.5.0]

**To Reproduce**

**Expected behavior**

work fine

**Screenshots**
![Screenshot_20240502_044035](https://github.com/springdoc/springdoc-openapi/assets/34833442/b199772f-2b04-4f6d-bc40-92bd0ddd7e41)
![Screenshot_20240502_044250](https://github.com/springdoc/springdoc-openapi/assets/34833442/987a8478-f8c3-4665-abdb-fb17f1a649b3)

Why are different versions referenced？？？

**Additional context**
- spring-boot 3.2.0
- spring-cloud 2023.0.0
- webflux

**Comment by bartveenstra** [comment]
Why is this closed? I am experiencing the same issue

**Comment by KaseiHaku** [comment]
> Why is this closed? I am experiencing the same issue

because i found the bug is not form springdoc, it is from my maven settings
you can use follow cmd to check where is wrong in your pom.xml config
shell> ./mvnw -pl your-module-name dependency:tree -Dverbose | cat -n | grep -iP ':swagger-annotations-jakarta:'
