### ISSUE TITLE
Attempting to add @SecurityScheme to annotation results in a NPE.

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#36]
Example: `@Target(AnnotationTarget.CLASS, AnnotationTarget.FILE)
@Retention(AnnotationRetention.RUNTIME)
@RestController
@RequestMapping("/api/v1/pdf")
@SecurityScheme(type = SecuritySchemeType.APIKEY, `in` = SecuritySchemeIn.HEADER,  name="Authorization", bearerFormat = "Bearer", description = "A core-auth Bearer token")
annotation class V1ApiController(
    @get:AliasFor(annotation = RestController::class)
    val value: String = ""
)`

components.getSecuritySchemes() on line 155 is null.

`Caused by: java.lang.NullPointerException
	at org.springdoc.core.GeneralInfoBuilder.addSecurityScheme(GeneralInfoBuilder.java:155) ~[springdoc-openapi-common-1.1.18.jar:?]
	at org.springdoc.core.GeneralInfoBuilder.calculateSecuritySchemes(GeneralInfoBuilder.java:124) ~[springdoc-openapi-common-1.1.18.jar:?]
	at org.springdoc.core.GeneralInfoBuilder.build(GeneralInfoBuilder.java:64) ~[springdoc-openapi-common-1.1.18.jar:?]
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:62) ~[springdoc-openapi-common-1.1.18.jar:?]
	at org.springdoc.api.OpenApiResource.openapiJson(OpenApiResource.java:53) ~[springdoc-openapi-core-1.1.18.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1039) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005) ~[spring-webmvc-5.1.9.RELEASE.jar:5.1.9.RELEASE]
	... 52 more`

**Comment by springdoc** [comment]
Hi, 
 Yes, the issue is confirmed and fixed.
 The fix is available on v1.1.19.
