### ISSUE TITLE
Possibility to specify custom schema examples.

### ISSUE THREAD

**Issue by ptahchiev** [springdoc/springdoc-openapi#457]
Here's my situation:
 - We are building a a REST API and we want to document it with SpringDoc/Swagger
 - Some of the APIs return `ProductDto` which is defined in a jar file and we have no access to the codebase of `ProductDto`.
 - The `ProductDto` has a field of type `MonetaryAmount` and we have registered a jackson module to deal with serialization/de-serialization of `MonetaryAmount`. So when the API is invoked we see this in the response:
````
  "price": {
    "amount": "5.00",
    "currency": "USD"
  },
````
however, the Swagger-UI and the generated schema shows this as an example:
````
    "price": {
      "code": "string",
      "defaultPaymentInfo": true,
      "subscriptionCode": "string",
      "saved": true,
      "paymentMode": {
        "id": "string",
        "code": "string",
        "name": "string",
        "description": "string",
        "method": {},
        "hopChargeUrl": "string",
        "cost": {
          "negativeOrZero": true,
          "positiveOrZero": true,
          "negative": true,
          "zero": true,
          "positive": true,
          "context": {
            "precision": 0,
            "fixedScale": true,
            "maxScale": 0,
            "empty": true,
            "providerName": "string"
          },
          "currency": {
            "defaultFractionDigits": 0,
            "numericCode": 0,
            "currencyCode": "string",
            "context": {
              "empty": true,
              "providerName": "string"
            }
          },
          "number": {
            "amountFractionNumerator": 0,
            "amountFractionDenominator": 0,
            "precision": 0,
            "scale": 0
          }
        }
      },
````
Is there a possibility to register something like `SchemaCustomizer` to provide custom snippet for fields of type `MonetaryAmount`?
We can't add annotations because we don't have access to the source-code and my wish was to actually deal with this in a central place, rather than going through all of our DTOs and adding custom annotations every time I see a field of type `MonetaryAmount`.

**Comment by bnasslahsen** [comment]
Hello,

 If we suppose, you are using this custom class for Schema mapping:

```java
public class CustomMonetaryAmount {

    @JsonProperty("amount") 
    final BigDecimal amount;
    
    @JsonProperty("currency") 
    final String currency;
    
}
```

You can then call:

```java
SpringDocUtils.replaceWithSchema(MonetaryAmount.class, CustomMonetaryAmount.class);
```

**Comment by ptahchiev** [comment]
Hi @bnasslahsen maybe I'm doing something wrong but the `replaceWithSchema` method requires an object of type `Schema` and the the `CustomMonetaryAmount` class you have given is not a `Schema` :(

**Comment by bnasslahsen** [comment]
I have edited my comment to replaceWithClass.
Can you tell if its working in your case?

**Comment by ptahchiev** [comment]
I added this:
```
    @Bean
    public OpenApiCustomiser defaultOpenApiCustomizer() {
        return openApi -> SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, CustomMonetaryAmount.class);
    }

    public class CustomMonetaryAmount {
        @JsonProperty("amount")
        private BigDecimal amount;

        @JsonProperty("currency")
        private String currency;

    }
```
but when I access the swagger I get this:
```
 2020-02-26 17:55:23,482 org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/storefront].[dispatcherServlet] [https-jsse-nio-127.0.0.1-8112-exec-8] ERROR: Servlet.service() for servlet [dispatcherServlet] in context with path [/storefront] threw exception [Request processing failed; nested exception is java.lang.IllegalArgumentException: Conflicting setter definitions for property "number": javax.money.MonetaryAmountFactory#setNumber(1 params) vs javax.money.MonetaryAmountFactory#setNumber(1 params)] with root cause
java.lang.IllegalArgumentException: Conflicting setter definitions for property "number": javax.money.MonetaryAmountFactory#setNumber(1 params) vs javax.money.MonetaryAmountFactory#setNumber(1 params)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getSetter(POJOPropertyBuilder.java:497)
	at com.fasterxml.jackson.databind.introspect.BeanPropertyDefinition.getMutator(BeanPropertyDefinition.java:203)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryMember(POJOPropertyBuilder.java:571)
	at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:542)
	at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:49)

```

**Comment by ptahchiev** [comment]
I've added this:
```
    @Bean
    public OpenApiBuilderCustomiser defaultOpenApiBuilderCustomizer() {
        return openApiBuilder -> {
            Json.mapper().addMixIn(MonetaryAmount.class, MonetaryAmountJsonMixIn.class);
        };
    }

    abstract class MonetaryAmountJsonMixIn {
        @JsonIgnore
        public abstract MonetaryAmountFactory<? extends MonetaryAmount> getFactory();
    }
```

to avoid the exception. However, the schema is still wrong:
```
"totalAmount": {
    "negativeOrZero": true,
    "positiveOrZero": true,
    "positive": true,
    "context": {
      "fixedScale": true,
      "maxScale": 0,
      "precision": 0,
      "empty": true,
      "providerName": "string"
    },
    "negative": true,
    "zero": true,
    "currency": {
      "currencyCode": "string",
      "context": {
        "empty": true,
        "providerName": "string"
      },
      "defaultFractionDigits": 0,
      "numericCode": 0
    },
    "number": {
      "amountFractionNumerator": 0,
      "amountFractionDenominator": 0,
      "precision": 0,
      "scale": 0
    }
  },
```

**Comment by bnasslahsen** [comment]
@ptahchiev, 

 You don't need to declare replaceWithClass using OpenApiCustomiser .
 Its better to declare it in static block, once yout application is started.
 Please have a look at my updated sample code provided, and tell us if its working for you.

**Comment by ptahchiev** [comment]
Hi @bnasslahsen it works with a static block, and it also works using an `OpenApiBuilderCustomizer` - one more reason for https://github.com/springdoc/springdoc-openapi/pull/451 to go in :))

**Comment by AnthonyGress** [comment]
How do you use SpringDocUtils? I don't see it as an import and can't find anything in the docs or online about how to use it, other than that same code snippet.

**Comment by bnasslahsen** [comment]
@AnthonyGress,

it's all documented here:
- https://springdoc.org/

And for concrete java samples, search for `SpringDocUtils` in this repo.
