### ISSUE TITLE
NPE: Upgrading from 1.3.4 version to any higher version causes Null Pointer Exception

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#723]
I am trying to upgrade to latest version from 1.3.4 to 1.40. But any version after 1.3.4 throws the below Null Pointer Exception

spring boot version - 2.2.7
springfoc-openapi-ui - 1.3.4 (this version works, newer version with same spring boot version doesnt work)

```java
java.lang.NullPointerException: null
	at io.swagger.v3.core.util.AnnotationsUtils.resolveSchemaFromType(AnnotationsUtils.java:571) ~[swagger-core-2.1.2.jar:2.1.2]
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1126) ~[swagger-core-2.1.2.jar:2.1.2]
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1116) ~[swagger-core-2.1.2.jar:2.1.2]
	at org.springdoc.core.GenericParameterBuilder.setSchema(GenericParameterBuilder.java:198) ~[springdoc-openapi-common-1.3.5.jar:1.3.5]
	at org.springdoc.core.GenericParameterBuilder.buildParameterFromDoc(GenericParameterBuilder.java:176) ~[springdoc-openapi-common-1.3.5.jar:1.3.5]
	at org.springdoc.core.AbstractRequestBuilder.build(AbstractRequestBuilder.java:189) ~[springdoc-openapi-common-1.3.5.jar:1.3.5]
	at org.springdoc.api.AbstractOpenApiResource.calculatePath(AbstractOpenApiResource.java:217) ~[springdoc-openapi-common-1.3.5.jar:1.3.5]
	at org.springdoc.webmvc.api.OpenApiResource.calculatePath(OpenApiResource.java:156) ~[springdoc-openapi-webmvc-core-1.3.5.jar:1.3.5]
	at org.springdoc.webmvc.api.OpenApiResource.getPaths(OpenApiResource.java:122) ~[springdoc-openapi-webmvc-core-1.3.5.jar:1.3.5]
	at org.springdoc.api.AbstractOpenApiResource.getOpenApi(AbstractOpenApiResource.java:140) ~[springdoc-openapi-common-1.3.5.jar:1.3.5]
	at org.springdoc.webmvc.api.OpenApiResource.openapiJson(OpenApiResource.java:106) ~[springdoc-openapi-webmvc-core-1.3.5.jar:1.3.5]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_212]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.35.jar:9.0.35]
```

**Comment by bnasslahsen** [comment]
Your stacktrace is using v1.3.5.
Use the last stable version for your upgrade: v1.4.0.

If you are still having the issue, please help to speed up problem diagnosis by providing as much information as possible:
- **Provide with a sample code (HelloController) or Test that reproduces the problem**: Minimal / reproducible project.
